/* Generated by Amaranth Yosys 0.50 (PyPI ver 0.50.0.0.post122, git sha1 b5170e139) */

(* top =  1  *)
(* src = "/tmp/ipykernel_13211/1946059917.py:98" *)
(* generator = "Amaranth" *)
module tt_um_lacesse_npu(uio_in, ena, clk, rst_n, uo_out, uio_out, uio_oe, ui_in);
  reg \$auto$verilog_backend.cc:2355:dump_module$1  = 0;
  reg [31:0] \$1 ;
  reg [1:0] \$2 ;
  reg [1:0] \$3 ;
  reg [1:0] \$4 ;
  reg [1:0] \$5 ;
  reg [31:0] \$6 ;
  (* src = "/tmp/ipykernel_13211/1946059917.py:30" *)
  reg [1:0] \$signal  = 2'h0;
  (* src = "/tmp/ipykernel_13211/1946059917.py:30" *)
  reg [1:0] \$signal$16  = 2'h0;
  (* src = "/tmp/ipykernel_13211/1946059917.py:31" *)
  reg [1:0] \$signal$18  = 2'h0;
  (* src = "/tmp/ipykernel_13211/1946059917.py:31" *)
  reg [1:0] \$signal$20  = 2'h0;
  (* src = "/tmp/ipykernel_13211/1946059917.py:101" *)
  input clk;
  wire clk;
  (* src = "/tmp/ipykernel_13211/1946059917.py:101" *)
  wire \clk$8 ;
  (* src = "/tmp/ipykernel_13211/1946059917.py:32" *)
  reg en;
  (* src = "/tmp/ipykernel_13211/1946059917.py:93" *)
  input ena;
  wire ena;
  (* src = "/tmp/ipykernel_13211/1946059917.py:34" *)
  wire [15:0] out00;
  (* src = "/tmp/ipykernel_13211/1946059917.py:35" *)
  wire [15:0] out01;
  (* src = "/tmp/ipykernel_13211/1946059917.py:36" *)
  wire [15:0] out10;
  (* src = "/tmp/ipykernel_13211/1946059917.py:37" *)
  wire [15:0] out11;
  (* src = "/tmp/ipykernel_13211/1946059917.py:120" *)
  reg [31:0] result_reg = 32'd0;
  (* src = "/tmp/ipykernel_13211/1946059917.py:28" *)
  reg [7:0] row0_in;
  (* src = "/tmp/ipykernel_13211/1946059917.py:29" *)
  reg [7:0] row1_in;
  (* src = "/tmp/ipykernel_13211/1946059917.py:101" *)
  wire rst;
  (* src = "/tmp/ipykernel_13211/1946059917.py:95" *)
  input rst_n;
  wire rst_n;
  (* src = "/tmp/ipykernel_13211/1946059917.py:111" *)
  reg [31:0] shift_reg = 32'd0;
  (* src = "/tmp/ipykernel_13211/1946059917.py:88" *)
  input [7:0] ui_in;
  wire [7:0] ui_in;
  (* src = "/tmp/ipykernel_13211/1946059917.py:90" *)
  input [7:0] uio_in;
  wire [7:0] uio_in;
  (* src = "/tmp/ipykernel_13211/1946059917.py:92" *)
  output [7:0] uio_oe;
  wire [7:0] uio_oe;
  (* src = "/tmp/ipykernel_13211/1946059917.py:91" *)
  output [7:0] uio_out;
  wire [7:0] uio_out;
  (* src = "/tmp/ipykernel_13211/1946059917.py:89" *)
  output [7:0] uo_out;
  wire [7:0] uo_out;
  (* init = 2'h0 *)
  (* src = "/tmp/ipykernel_13211/1946059917.py:114" *)
  wire [1:0] w00_reg;
  (* init = 2'h0 *)
  (* src = "/tmp/ipykernel_13211/1946059917.py:115" *)
  wire [1:0] w01_reg;
  (* init = 2'h0 *)
  (* src = "/tmp/ipykernel_13211/1946059917.py:116" *)
  wire [1:0] w10_reg;
  (* init = 2'h0 *)
  (* src = "/tmp/ipykernel_13211/1946059917.py:117" *)
  wire [1:0] w11_reg;
  (* src = "/tmp/ipykernel_13211/1946059917.py:111" *)
  always @(posedge clk)
    shift_reg <= \$1 ;
  (* src = "/tmp/ipykernel_13211/1946059917.py:114" *)
  always @(posedge clk)
    \$signal  <= \$2 ;
  (* src = "/tmp/ipykernel_13211/1946059917.py:115" *)
  always @(posedge clk)
    \$signal$16  <= \$3 ;
  (* src = "/tmp/ipykernel_13211/1946059917.py:116" *)
  always @(posedge clk)
    \$signal$18  <= \$4 ;
  (* src = "/tmp/ipykernel_13211/1946059917.py:117" *)
  always @(posedge clk)
    \$signal$20  <= \$5 ;
  (* src = "/tmp/ipykernel_13211/1946059917.py:120" *)
  always @(posedge clk)
    result_reg <= \$6 ;
  assign rst = ~ (* src = "/tmp/ipykernel_13211/1946059917.py:104" *) rst_n;
  (* src = "/tmp/ipykernel_13211/1946059917.py:107" *)
  \tt_um_lacesse_npu.array  array (
    .clk(clk),
    .en(en),
    .out00(out00),
    .out01(out01),
    .out10(out10),
    .out11(out11),
    .rst(rst),
    .w(\$signal ),
    .\w$2 (\$signal$16 ),
    .\w$4 (\$signal$18 ),
    .\w$6 (\$signal$20 ),
    .x_in(row0_in),
    .\x_in$17 (row1_in)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    en = 1'h0;
    if (ui_in[1]) begin
      casez (ui_in[4:3])
        2'h1:
            /* empty */;
        2'h2:
            en = 1'h1;
      endcase
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$1  = shift_reg;
    if (ui_in[0]) begin
      \$1  = { shift_reg[27:0], ui_in[7:4] };
    end
    if (rst) begin
      \$1  = 32'd0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$2  = \$signal ;
    if (ui_in[1]) begin
      casez (ui_in[4:3])
        2'h1:
            \$2  = shift_reg[1:0];
      endcase
    end
    if (rst) begin
      \$2  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$3  = \$signal$16 ;
    if (ui_in[1]) begin
      casez (ui_in[4:3])
        2'h1:
            \$3  = shift_reg[9:8];
      endcase
    end
    if (rst) begin
      \$3  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$4  = \$signal$18 ;
    if (ui_in[1]) begin
      casez (ui_in[4:3])
        2'h1:
            \$4  = shift_reg[17:16];
      endcase
    end
    if (rst) begin
      \$4  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$5  = \$signal$20 ;
    if (ui_in[1]) begin
      casez (ui_in[4:3])
        2'h1:
            \$5  = shift_reg[25:24];
      endcase
    end
    if (rst) begin
      \$5  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$6  = result_reg;
    if (ui_in[1]) begin
      casez (ui_in[4:3])
        2'h1:
            /* empty */;
        2'h2:
            \$6  = { out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00 };
        2'h3:
            (* full_case = 32'd1 *)
            casez (shift_reg[1:0])
              2'h0:
                  \$6  = { out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00 };
              2'h1:
                  \$6  = { out01[15], out01[15], out01[15], out01[15], out01[15], out01[15], out01[15], out01[15], out01[15], out01[15], out01[15], out01[15], out01[15], out01[15], out01[15], out01[15], out01 };
              2'h2:
                  \$6  = { out10[15], out10[15], out10[15], out10[15], out10[15], out10[15], out10[15], out10[15], out10[15], out10[15], out10[15], out10[15], out10[15], out10[15], out10[15], out10[15], out10 };
              2'h3:
                  \$6  = { out11[15], out11[15], out11[15], out11[15], out11[15], out11[15], out11[15], out11[15], out11[15], out11[15], out11[15], out11[15], out11[15], out11[15], out11[15], out11[15], out11 };
            endcase
      endcase
    end
    if (rst) begin
      \$6  = 32'd0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    row0_in = 8'h00;
    if (ui_in[1]) begin
      casez (ui_in[4:3])
        2'h1:
            /* empty */;
        2'h2:
            row0_in = shift_reg[7:0];
      endcase
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    row1_in = 8'h00;
    if (ui_in[1]) begin
      casez (ui_in[4:3])
        2'h1:
            /* empty */;
        2'h2:
            row1_in = shift_reg[15:8];
      endcase
    end
  end
  assign \clk$8  = clk;
  assign w00_reg = \$signal ;
  assign w01_reg = \$signal$16 ;
  assign w10_reg = \$signal$18 ;
  assign w11_reg = \$signal$20 ;
  assign uo_out = result_reg[7:0];
  assign uio_out = 8'h00;
  assign uio_oe = 8'hff;
endmodule

(* src = "/tmp/ipykernel_13211/1946059917.py:40" *)
(* generator = "Amaranth" *)
module \tt_um_lacesse_npu.array (rst, x_in, \x_in$17 , en, w, \w$2 , \w$4 , \w$6 , out00, out01, out10, out11, clk);
  (* src = "/tmp/ipykernel_13211/1946059917.py:30" *)
  wire [1:0] \$signal ;
  (* src = "/tmp/ipykernel_13211/1946059917.py:30" *)
  wire [1:0] \$signal$3 ;
  (* src = "/tmp/ipykernel_13211/1946059917.py:31" *)
  wire [1:0] \$signal$5 ;
  (* src = "/tmp/ipykernel_13211/1946059917.py:31" *)
  wire [1:0] \$signal$7 ;
  (* src = "/tmp/ipykernel_13211/1946059917.py:11" *)
  wire [15:0] acc;
  (* src = "/tmp/ipykernel_13211/1946059917.py:11" *)
  wire [15:0] \acc$24 ;
  (* src = "/tmp/ipykernel_13211/1946059917.py:11" *)
  wire [15:0] \acc$26 ;
  (* src = "/tmp/ipykernel_13211/1946059917.py:11" *)
  wire [15:0] \acc$28 ;
  (* src = "/tmp/ipykernel_13211/1946059917.py:101" *)
  input clk;
  wire clk;
  (* src = "/tmp/ipykernel_13211/1946059917.py:10" *)
  input en;
  wire en;
  (* src = "/tmp/ipykernel_13211/1946059917.py:10" *)
  wire \en$10 ;
  (* src = "/tmp/ipykernel_13211/1946059917.py:10" *)
  wire \en$11 ;
  (* src = "/tmp/ipykernel_13211/1946059917.py:10" *)
  wire \en$12 ;
  (* src = "/tmp/ipykernel_13211/1946059917.py:32" *)
  wire \en$9 ;
  (* src = "/tmp/ipykernel_13211/1946059917.py:11" *)
  output [15:0] out00;
  wire [15:0] out00;
  (* src = "/tmp/ipykernel_13211/1946059917.py:11" *)
  output [15:0] out01;
  wire [15:0] out01;
  (* src = "/tmp/ipykernel_13211/1946059917.py:11" *)
  output [15:0] out10;
  wire [15:0] out10;
  (* src = "/tmp/ipykernel_13211/1946059917.py:11" *)
  output [15:0] out11;
  wire [15:0] out11;
  (* src = "/tmp/ipykernel_13211/1946059917.py:28" *)
  wire [7:0] row0_in;
  (* src = "/tmp/ipykernel_13211/1946059917.py:29" *)
  wire [7:0] row1_in;
  (* src = "/tmp/ipykernel_13211/1946059917.py:101" *)
  input rst;
  wire rst;
  (* src = "/tmp/ipykernel_13211/1946059917.py:30" *)
  input [1:0] w;
  wire [1:0] w;
  (* src = "/tmp/ipykernel_13211/1946059917.py:30" *)
  input [1:0] \w$2 ;
  wire [1:0] \w$2 ;
  (* src = "/tmp/ipykernel_13211/1946059917.py:31" *)
  input [1:0] \w$4 ;
  wire [1:0] \w$4 ;
  (* src = "/tmp/ipykernel_13211/1946059917.py:31" *)
  input [1:0] \w$6 ;
  wire [1:0] \w$6 ;
  (* src = "/tmp/ipykernel_13211/1946059917.py:28" *)
  input [7:0] x_in;
  wire [7:0] x_in;
  (* src = "/tmp/ipykernel_13211/1946059917.py:7" *)
  wire [7:0] \x_in$15 ;
  (* src = "/tmp/ipykernel_13211/1946059917.py:29" *)
  input [7:0] \x_in$17 ;
  wire [7:0] \x_in$17 ;
  (* src = "/tmp/ipykernel_13211/1946059917.py:7" *)
  wire [7:0] \x_in$19 ;
  (* src = "/tmp/ipykernel_13211/1946059917.py:8" *)
  wire [7:0] x_out;
  (* src = "/tmp/ipykernel_13211/1946059917.py:8" *)
  wire [7:0] \x_out$20 ;
  (* src = "/tmp/ipykernel_13211/1946059917.py:41" *)
  \tt_um_lacesse_npu.array.mac00  mac00 (
    .acc(out00),
    .clk(clk),
    .en(en),
    .rst(rst),
    .w(w),
    .x_in(x_in),
    .x_out(\x_in$15 )
  );
  (* src = "/tmp/ipykernel_13211/1946059917.py:42" *)
  \tt_um_lacesse_npu.array.mac01  mac01 (
    .acc(out01),
    .clk(clk),
    .en(en),
    .rst(rst),
    .w(\w$2 ),
    .x_in(\x_in$15 )
  );
  (* src = "/tmp/ipykernel_13211/1946059917.py:43" *)
  \tt_um_lacesse_npu.array.mac10  mac10 (
    .acc(out10),
    .clk(clk),
    .en(en),
    .rst(rst),
    .w(\w$4 ),
    .x_in(\x_in$17 ),
    .x_out(\x_in$19 )
  );
  (* src = "/tmp/ipykernel_13211/1946059917.py:44" *)
  \tt_um_lacesse_npu.array.mac11  mac11 (
    .acc(out11),
    .clk(clk),
    .en(en),
    .rst(rst),
    .w(\w$6 ),
    .x_in(\x_in$19 )
  );
  assign \$signal  = w;
  assign \$signal$3  = \w$2 ;
  assign \$signal$5  = \w$4 ;
  assign \$signal$7  = \w$6 ;
  assign \en$9  = en;
  assign \en$10  = en;
  assign \en$11  = en;
  assign \en$12  = en;
  assign row0_in = x_in;
  assign x_out = \x_in$15 ;
  assign row1_in = \x_in$17 ;
  assign \x_out$20  = \x_in$19 ;
  assign acc = out00;
  assign \acc$24  = out01;
  assign \acc$26  = out10;
  assign \acc$28  = out11;
endmodule

(* src = "/tmp/ipykernel_13211/1946059917.py:14" *)
(* generator = "Amaranth" *)
module \tt_um_lacesse_npu.array.mac00 (rst, x_in, en, w, x_out, acc, clk);
  reg \$auto$verilog_backend.cc:2355:dump_module$2  = 0;
  wire \$1 ;
  wire \$2 ;
  wire [16:0] \$3 ;
  wire [16:0] \$4 ;
  reg [7:0] \$5 ;
  reg [15:0] \$6 ;
  (* src = "/tmp/ipykernel_13211/1946059917.py:11" *)
  output [15:0] acc;
  reg [15:0] acc = 16'h0000;
  (* src = "/tmp/ipykernel_13211/1946059917.py:101" *)
  input clk;
  wire clk;
  (* src = "/tmp/ipykernel_13211/1946059917.py:10" *)
  input en;
  wire en;
  (* src = "/tmp/ipykernel_13211/1946059917.py:101" *)
  input rst;
  wire rst;
  (* src = "/tmp/ipykernel_13211/1946059917.py:9" *)
  input [1:0] w;
  wire [1:0] w;
  (* src = "/tmp/ipykernel_13211/1946059917.py:7" *)
  input [7:0] x_in;
  wire [7:0] x_in;
  (* src = "/tmp/ipykernel_13211/1946059917.py:8" *)
  output [7:0] x_out;
  reg [7:0] x_out = 8'h00;
  assign \$4  = $signed(acc) - (* src = "/tmp/ipykernel_13211/1946059917.py:21" *) $signed(x_in);
  (* src = "/tmp/ipykernel_13211/1946059917.py:8" *)
  always @(posedge clk)
    x_out <= \$5 ;
  (* src = "/tmp/ipykernel_13211/1946059917.py:11" *)
  always @(posedge clk)
    acc <= \$6 ;
  assign \$1  = w == (* src = "/tmp/ipykernel_13211/1946059917.py:18" *) 1'h1;
  assign \$2  = w == (* src = "/tmp/ipykernel_13211/1946059917.py:20" *) 2'h3;
  assign \$3  = $signed(acc) + (* src = "/tmp/ipykernel_13211/1946059917.py:19" *) $signed(x_in);
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    \$5  = x_in;
    if (rst) begin
      \$5  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    \$6  = acc;
    if (en) begin
      if (\$1 ) begin
        \$6  = \$3 [15:0];
      end else if (\$2 ) begin
        \$6  = \$4 [15:0];
      end
    end
    if (rst) begin
      \$6  = 16'h0000;
    end
  end
endmodule

(* src = "/tmp/ipykernel_13211/1946059917.py:14" *)
(* generator = "Amaranth" *)
module \tt_um_lacesse_npu.array.mac01 (rst, en, w, x_in, acc, clk);
  reg \$auto$verilog_backend.cc:2355:dump_module$3  = 0;
  wire \$1 ;
  wire \$2 ;
  wire [16:0] \$3 ;
  wire [16:0] \$4 ;
  reg [7:0] \$5 ;
  reg [15:0] \$6 ;
  (* src = "/tmp/ipykernel_13211/1946059917.py:11" *)
  output [15:0] acc;
  reg [15:0] acc = 16'h0000;
  (* src = "/tmp/ipykernel_13211/1946059917.py:101" *)
  input clk;
  wire clk;
  (* src = "/tmp/ipykernel_13211/1946059917.py:10" *)
  input en;
  wire en;
  (* src = "/tmp/ipykernel_13211/1946059917.py:101" *)
  input rst;
  wire rst;
  (* src = "/tmp/ipykernel_13211/1946059917.py:9" *)
  input [1:0] w;
  wire [1:0] w;
  (* src = "/tmp/ipykernel_13211/1946059917.py:7" *)
  input [7:0] x_in;
  wire [7:0] x_in;
  (* src = "/tmp/ipykernel_13211/1946059917.py:8" *)
  reg [7:0] x_out = 8'h00;
  assign \$4  = $signed(acc) - (* src = "/tmp/ipykernel_13211/1946059917.py:21" *) $signed(x_in);
  (* src = "/tmp/ipykernel_13211/1946059917.py:8" *)
  always @(posedge clk)
    x_out <= \$5 ;
  (* src = "/tmp/ipykernel_13211/1946059917.py:11" *)
  always @(posedge clk)
    acc <= \$6 ;
  assign \$1  = w == (* src = "/tmp/ipykernel_13211/1946059917.py:18" *) 1'h1;
  assign \$2  = w == (* src = "/tmp/ipykernel_13211/1946059917.py:20" *) 2'h3;
  assign \$3  = $signed(acc) + (* src = "/tmp/ipykernel_13211/1946059917.py:19" *) $signed(x_in);
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$3 ) begin end
    \$5  = x_in;
    if (rst) begin
      \$5  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$3 ) begin end
    \$6  = acc;
    if (en) begin
      if (\$1 ) begin
        \$6  = \$3 [15:0];
      end else if (\$2 ) begin
        \$6  = \$4 [15:0];
      end
    end
    if (rst) begin
      \$6  = 16'h0000;
    end
  end
endmodule

(* src = "/tmp/ipykernel_13211/1946059917.py:14" *)
(* generator = "Amaranth" *)
module \tt_um_lacesse_npu.array.mac10 (rst, x_in, en, w, x_out, acc, clk);
  reg \$auto$verilog_backend.cc:2355:dump_module$4  = 0;
  wire \$1 ;
  wire \$2 ;
  wire [16:0] \$3 ;
  wire [16:0] \$4 ;
  reg [7:0] \$5 ;
  reg [15:0] \$6 ;
  (* src = "/tmp/ipykernel_13211/1946059917.py:11" *)
  output [15:0] acc;
  reg [15:0] acc = 16'h0000;
  (* src = "/tmp/ipykernel_13211/1946059917.py:101" *)
  input clk;
  wire clk;
  (* src = "/tmp/ipykernel_13211/1946059917.py:10" *)
  input en;
  wire en;
  (* src = "/tmp/ipykernel_13211/1946059917.py:101" *)
  input rst;
  wire rst;
  (* src = "/tmp/ipykernel_13211/1946059917.py:9" *)
  input [1:0] w;
  wire [1:0] w;
  (* src = "/tmp/ipykernel_13211/1946059917.py:7" *)
  input [7:0] x_in;
  wire [7:0] x_in;
  (* src = "/tmp/ipykernel_13211/1946059917.py:8" *)
  output [7:0] x_out;
  reg [7:0] x_out = 8'h00;
  assign \$4  = $signed(acc) - (* src = "/tmp/ipykernel_13211/1946059917.py:21" *) $signed(x_in);
  (* src = "/tmp/ipykernel_13211/1946059917.py:8" *)
  always @(posedge clk)
    x_out <= \$5 ;
  (* src = "/tmp/ipykernel_13211/1946059917.py:11" *)
  always @(posedge clk)
    acc <= \$6 ;
  assign \$1  = w == (* src = "/tmp/ipykernel_13211/1946059917.py:18" *) 1'h1;
  assign \$2  = w == (* src = "/tmp/ipykernel_13211/1946059917.py:20" *) 2'h3;
  assign \$3  = $signed(acc) + (* src = "/tmp/ipykernel_13211/1946059917.py:19" *) $signed(x_in);
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$4 ) begin end
    \$5  = x_in;
    if (rst) begin
      \$5  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$4 ) begin end
    \$6  = acc;
    if (en) begin
      if (\$1 ) begin
        \$6  = \$3 [15:0];
      end else if (\$2 ) begin
        \$6  = \$4 [15:0];
      end
    end
    if (rst) begin
      \$6  = 16'h0000;
    end
  end
endmodule

(* src = "/tmp/ipykernel_13211/1946059917.py:14" *)
(* generator = "Amaranth" *)
module \tt_um_lacesse_npu.array.mac11 (rst, en, w, x_in, acc, clk);
  reg \$auto$verilog_backend.cc:2355:dump_module$5  = 0;
  wire \$1 ;
  wire \$2 ;
  wire [16:0] \$3 ;
  wire [16:0] \$4 ;
  reg [7:0] \$5 ;
  reg [15:0] \$6 ;
  (* src = "/tmp/ipykernel_13211/1946059917.py:11" *)
  output [15:0] acc;
  reg [15:0] acc = 16'h0000;
  (* src = "/tmp/ipykernel_13211/1946059917.py:101" *)
  input clk;
  wire clk;
  (* src = "/tmp/ipykernel_13211/1946059917.py:10" *)
  input en;
  wire en;
  (* src = "/tmp/ipykernel_13211/1946059917.py:101" *)
  input rst;
  wire rst;
  (* src = "/tmp/ipykernel_13211/1946059917.py:9" *)
  input [1:0] w;
  wire [1:0] w;
  (* src = "/tmp/ipykernel_13211/1946059917.py:7" *)
  input [7:0] x_in;
  wire [7:0] x_in;
  (* src = "/tmp/ipykernel_13211/1946059917.py:8" *)
  reg [7:0] x_out = 8'h00;
  assign \$4  = $signed(acc) - (* src = "/tmp/ipykernel_13211/1946059917.py:21" *) $signed(x_in);
  (* src = "/tmp/ipykernel_13211/1946059917.py:8" *)
  always @(posedge clk)
    x_out <= \$5 ;
  (* src = "/tmp/ipykernel_13211/1946059917.py:11" *)
  always @(posedge clk)
    acc <= \$6 ;
  assign \$1  = w == (* src = "/tmp/ipykernel_13211/1946059917.py:18" *) 1'h1;
  assign \$2  = w == (* src = "/tmp/ipykernel_13211/1946059917.py:20" *) 2'h3;
  assign \$3  = $signed(acc) + (* src = "/tmp/ipykernel_13211/1946059917.py:19" *) $signed(x_in);
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$5 ) begin end
    \$5  = x_in;
    if (rst) begin
      \$5  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$5 ) begin end
    \$6  = acc;
    if (en) begin
      if (\$1 ) begin
        \$6  = \$3 [15:0];
      end else if (\$2 ) begin
        \$6  = \$4 [15:0];
      end
    end
    if (rst) begin
      \$6  = 16'h0000;
    end
  end
endmodule
