/* Generated by Amaranth Yosys 0.50 (PyPI ver 0.50.0.0.post122, git sha1 b5170e139) */

(* top =  1  *)
(* src = "/tmp/ipykernel_3846/3191868895.py:17" *)
(* generator = "Amaranth" *)
module tt_um_lacesse_npu(uio_in, ena, clk, rst_n, uo_out, uio_out, uio_oe, ui_in);
  reg \$auto$verilog_backend.cc:2355:dump_module$1  = 0;
  reg [31:0] \$1 ;
  (* src = "/tmp/ipykernel_3846/3191868895.py:21" *)
  input clk;
  wire clk;
  (* src = "/tmp/ipykernel_3846/3191868895.py:21" *)
  wire \clk$8 ;
  (* src = "/tmp/ipykernel_3846/883141529.py:8" *)
  wire [9:0] cmd_func_id;
  (* src = "/tmp/ipykernel_3846/883141529.py:9" *)
  reg [31:0] cmd_rs1 = 32'd0;
  (* src = "/tmp/ipykernel_3846/883141529.py:7" *)
  wire cmd_valid;
  (* src = "/tmp/ipykernel_3846/3191868895.py:12" *)
  input ena;
  wire ena;
  (* src = "/tmp/ipykernel_3846/883141529.py:13" *)
  wire [31:0] rsp_rd;
  (* src = "/tmp/ipykernel_3846/3191868895.py:21" *)
  wire rst;
  (* src = "/tmp/ipykernel_3846/3191868895.py:14" *)
  input rst_n;
  wire rst_n;
  (* init = 32'd0 *)
  (* src = "/tmp/ipykernel_3846/3191868895.py:30" *)
  wire [31:0] shift_reg;
  (* src = "/tmp/ipykernel_3846/3191868895.py:7" *)
  input [7:0] ui_in;
  wire [7:0] ui_in;
  (* src = "/tmp/ipykernel_3846/3191868895.py:9" *)
  input [7:0] uio_in;
  wire [7:0] uio_in;
  (* src = "/tmp/ipykernel_3846/3191868895.py:11" *)
  output [7:0] uio_oe;
  wire [7:0] uio_oe;
  (* src = "/tmp/ipykernel_3846/3191868895.py:10" *)
  output [7:0] uio_out;
  wire [7:0] uio_out;
  (* src = "/tmp/ipykernel_3846/3191868895.py:8" *)
  output [7:0] uo_out;
  wire [7:0] uo_out;
  assign rst = ~ (* src = "/tmp/ipykernel_3846/3191868895.py:24" *) rst_n;
  (* src = "/tmp/ipykernel_3846/3191868895.py:30" *)
  always @(posedge clk)
    cmd_rs1 <= \$1 ;
  (* src = "/tmp/ipykernel_3846/3191868895.py:27" *)
  \tt_um_lacesse_npu.npu  npu (
    .clk(clk),
    .cmd_rs1(cmd_rs1),
    .\port$0$3 (ui_in[3:1]),
    .rsp_rd(rsp_rd),
    .rst(rst)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$1  = cmd_rs1;
    if (ui_in[0]) begin
      \$1  = { cmd_rs1[27:0], ui_in[7:4] };
    end
    if (rst) begin
      \$1  = 32'd0;
    end
  end
  assign \clk$8  = clk;
  assign cmd_valid = ui_in[1];
  assign cmd_func_id = { 8'h00, ui_in[3:2] };
  assign shift_reg = cmd_rs1;
  assign uo_out = rsp_rd[7:0];
  assign uio_out = 8'h00;
  assign uio_oe = 8'hff;
endmodule

(* src = "/tmp/ipykernel_3846/883141529.py:16" *)
(* generator = "Amaranth" *)
module \tt_um_lacesse_npu.npu (clk, rst, cmd_rs1, rsp_rd, \port$0$3 );
  reg \$auto$verilog_backend.cc:2355:dump_module$2  = 0;
  wire \$1 ;
  wire \$2 ;
  wire \$3 ;
  wire \$4 ;
  reg \$5 ;
  reg [31:0] \$6 ;
  (* src = "/tmp/ipykernel_3846/3191868895.py:21" *)
  input clk;
  wire clk;
  (* src = "/tmp/ipykernel_3846/883141529.py:8" *)
  wire [9:0] cmd_func_id;
  (* src = "/tmp/ipykernel_3846/883141529.py:9" *)
  input [31:0] cmd_rs1;
  wire [31:0] cmd_rs1;
  (* src = "/tmp/ipykernel_3846/883141529.py:10" *)
  wire [31:0] cmd_rs2;
  (* src = "/tmp/ipykernel_3846/883141529.py:7" *)
  wire cmd_valid;
  (* src = "/tmp/ipykernel_3846/1200065306.py:45" *)
  reg en;
  (* src = "/tmp/ipykernel_3846/1200065306.py:48" *)
  wire [15:0] out00;
  input [2:0] \port$0$3 ;
  wire [2:0] \port$0$3 ;
  (* src = "/tmp/ipykernel_3846/1200065306.py:35" *)
  reg [7:0] row0_in;
  (* src = "/tmp/ipykernel_3846/1200065306.py:36" *)
  reg [7:0] row1_in;
  (* src = "/tmp/ipykernel_3846/883141529.py:13" *)
  output [31:0] rsp_rd;
  reg [31:0] rsp_rd = 32'd0;
  (* src = "/tmp/ipykernel_3846/883141529.py:12" *)
  reg rsp_valid = 1'h0;
  (* src = "/tmp/ipykernel_3846/3191868895.py:21" *)
  input rst;
  wire rst;
  (* src = "/tmp/ipykernel_3846/1200065306.py:39" *)
  reg [1:0] w00;
  (* src = "/tmp/ipykernel_3846/1200065306.py:40" *)
  reg [1:0] w01;
  (* src = "/tmp/ipykernel_3846/1200065306.py:41" *)
  reg [1:0] w10;
  (* src = "/tmp/ipykernel_3846/1200065306.py:42" *)
  reg [1:0] w11;
  assign \$4  = \port$0$3 [2:1] == (* src = "/tmp/ipykernel_3846/883141529.py:36" *) 2'h2;
  (* src = "/tmp/ipykernel_3846/883141529.py:12" *)
  always @(posedge clk)
    rsp_valid <= \$5 ;
  (* src = "/tmp/ipykernel_3846/883141529.py:13" *)
  always @(posedge clk)
    rsp_rd <= \$6 ;
  assign \$1  = \port$0$3 [2:1] == (* src = "/tmp/ipykernel_3846/883141529.py:25" *) 1'h1;
  assign \$2  = \port$0$3 [2:1] == (* src = "/tmp/ipykernel_3846/883141529.py:36" *) 2'h2;
  assign \$3  = \port$0$3 [2:1] == (* src = "/tmp/ipykernel_3846/883141529.py:25" *) 1'h1;
  (* src = "/tmp/ipykernel_3846/883141529.py:18" *)
  \tt_um_lacesse_npu.npu.array  array (
    .clk(clk),
    .en(en),
    .out00(out00),
    .rst(rst),
    .w(w00),
    .\w$12 (w10),
    .\w$16 (w11),
    .\w$8 (w01),
    .x_in(row0_in),
    .\x_in$22 (row1_in)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    \$5  = 1'h0;
    if (\port$0$3 [0]) begin
      if (\$1 ) begin
        \$5  = 1'h1;
      end else if (\$2 ) begin
        \$5  = 1'h1;
      end
    end
    if (rst) begin
      \$5  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    \$6  = rsp_rd;
    if (\port$0$3 [0]) begin
      if (\$1 ) begin
        \$6  = 32'd0;
      end else if (\$2 ) begin
        \$6  = { out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00 };
      end
    end
    if (rst) begin
      \$6  = 32'd0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    w00 = 2'h0;
    if (\port$0$3 [0]) begin
      if (\$3 ) begin
        w00 = cmd_rs1[1:0];
      end
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    w01 = 2'h0;
    if (\port$0$3 [0]) begin
      if (\$3 ) begin
        w01 = cmd_rs1[9:8];
      end
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    w10 = 2'h0;
    if (\port$0$3 [0]) begin
      if (\$3 ) begin
        w10 = cmd_rs1[17:16];
      end
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    w11 = 2'h0;
    if (\port$0$3 [0]) begin
      if (\$3 ) begin
        w11 = cmd_rs1[25:24];
      end
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    row0_in = 8'h00;
    if (\port$0$3 [0]) begin
      if (\$3 ) begin
      end else if (\$4 ) begin
        row0_in = cmd_rs1[7:0];
      end
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    row1_in = 8'h00;
    if (\port$0$3 [0]) begin
      if (\$3 ) begin
      end else if (\$4 ) begin
        row1_in = 8'h00;
      end
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    en = 1'h0;
    if (\port$0$3 [0]) begin
      if (\$3 ) begin
      end else if (\$4 ) begin
        en = 1'h1;
      end
    end
  end
  assign cmd_valid = \port$0$3 [0];
  assign cmd_func_id = { 8'h00, \port$0$3 [2:1] };
  assign cmd_rs2 = 32'd0;
endmodule

(* src = "/tmp/ipykernel_3846/1200065306.py:54" *)
(* generator = "Amaranth" *)
module \tt_um_lacesse_npu.npu.array (rst, w, \w$8 , \w$12 , \w$16 , x_in, \x_in$22 , en, out00, clk);
  (* src = "/tmp/ipykernel_3846/1200065306.py:12" *)
  wire [15:0] acc;
  (* src = "/tmp/ipykernel_3846/1200065306.py:12" *)
  wire [15:0] \acc$29 ;
  (* src = "/tmp/ipykernel_3846/1200065306.py:12" *)
  wire [15:0] \acc$31 ;
  (* src = "/tmp/ipykernel_3846/1200065306.py:12" *)
  wire [15:0] \acc$33 ;
  (* src = "/tmp/ipykernel_3846/1200065306.py:10" *)
  wire clear;
  (* src = "/tmp/ipykernel_3846/1200065306.py:44" *)
  wire \clear$1 ;
  (* src = "/tmp/ipykernel_3846/1200065306.py:10" *)
  wire \clear$10 ;
  (* src = "/tmp/ipykernel_3846/1200065306.py:10" *)
  wire \clear$14 ;
  (* src = "/tmp/ipykernel_3846/1200065306.py:10" *)
  wire \clear$6 ;
  (* src = "/tmp/ipykernel_3846/3191868895.py:21" *)
  input clk;
  wire clk;
  (* src = "/tmp/ipykernel_3846/1200065306.py:11" *)
  input en;
  wire en;
  (* src = "/tmp/ipykernel_3846/1200065306.py:11" *)
  wire \en$11 ;
  (* src = "/tmp/ipykernel_3846/1200065306.py:11" *)
  wire \en$15 ;
  (* src = "/tmp/ipykernel_3846/1200065306.py:45" *)
  wire \en$3 ;
  (* src = "/tmp/ipykernel_3846/1200065306.py:11" *)
  wire \en$7 ;
  (* src = "/tmp/ipykernel_3846/1200065306.py:12" *)
  output [15:0] out00;
  wire [15:0] out00;
  (* src = "/tmp/ipykernel_3846/1200065306.py:49" *)
  wire [15:0] out01;
  (* src = "/tmp/ipykernel_3846/1200065306.py:50" *)
  wire [15:0] out10;
  (* src = "/tmp/ipykernel_3846/1200065306.py:51" *)
  wire [15:0] out11;
  (* src = "/tmp/ipykernel_3846/1200065306.py:35" *)
  wire [7:0] row0_in;
  (* src = "/tmp/ipykernel_3846/1200065306.py:36" *)
  wire [7:0] row1_in;
  (* src = "/tmp/ipykernel_3846/3191868895.py:21" *)
  input rst;
  wire rst;
  (* src = "/tmp/ipykernel_3846/1200065306.py:39" *)
  input [1:0] w;
  wire [1:0] w;
  (* src = "/tmp/ipykernel_3846/1200065306.py:41" *)
  input [1:0] \w$12 ;
  wire [1:0] \w$12 ;
  (* src = "/tmp/ipykernel_3846/1200065306.py:42" *)
  input [1:0] \w$16 ;
  wire [1:0] \w$16 ;
  (* src = "/tmp/ipykernel_3846/1200065306.py:40" *)
  input [1:0] \w$8 ;
  wire [1:0] \w$8 ;
  (* src = "/tmp/ipykernel_3846/1200065306.py:39" *)
  wire [1:0] w00;
  (* src = "/tmp/ipykernel_3846/1200065306.py:40" *)
  wire [1:0] w01;
  (* src = "/tmp/ipykernel_3846/1200065306.py:41" *)
  wire [1:0] w10;
  (* src = "/tmp/ipykernel_3846/1200065306.py:42" *)
  wire [1:0] w11;
  (* src = "/tmp/ipykernel_3846/1200065306.py:35" *)
  input [7:0] x_in;
  wire [7:0] x_in;
  (* src = "/tmp/ipykernel_3846/1200065306.py:7" *)
  wire [7:0] \x_in$20 ;
  (* src = "/tmp/ipykernel_3846/1200065306.py:36" *)
  input [7:0] \x_in$22 ;
  wire [7:0] \x_in$22 ;
  (* src = "/tmp/ipykernel_3846/1200065306.py:7" *)
  wire [7:0] \x_in$24 ;
  (* src = "/tmp/ipykernel_3846/1200065306.py:8" *)
  wire [7:0] x_out;
  (* src = "/tmp/ipykernel_3846/1200065306.py:8" *)
  wire [7:0] \x_out$25 ;
  (* src = "/tmp/ipykernel_3846/1200065306.py:57" *)
  \tt_um_lacesse_npu.npu.array.mac00  mac00 (
    .acc(out00),
    .clk(clk),
    .en(en),
    .rst(rst),
    .w(w),
    .x_in(x_in),
    .x_out(\x_in$20 )
  );
  (* src = "/tmp/ipykernel_3846/1200065306.py:58" *)
  \tt_um_lacesse_npu.npu.array.mac01  mac01 (
    .acc(out01),
    .clk(clk),
    .en(en),
    .rst(rst),
    .w(\w$8 ),
    .x_in(\x_in$20 )
  );
  (* src = "/tmp/ipykernel_3846/1200065306.py:59" *)
  \tt_um_lacesse_npu.npu.array.mac10  mac10 (
    .acc(out10),
    .clk(clk),
    .en(en),
    .rst(rst),
    .w(\w$12 ),
    .x_in(\x_in$22 ),
    .x_out(\x_in$24 )
  );
  (* src = "/tmp/ipykernel_3846/1200065306.py:60" *)
  \tt_um_lacesse_npu.npu.array.mac11  mac11 (
    .acc(out11),
    .clk(clk),
    .en(en),
    .rst(rst),
    .w(\w$16 ),
    .x_in(\x_in$24 )
  );
  assign clear = 1'h0;
  assign \clear$1  = 1'h0;
  assign \en$3  = en;
  assign w00 = w;
  assign \clear$6  = 1'h0;
  assign \en$7  = en;
  assign w01 = \w$8 ;
  assign \clear$10  = 1'h0;
  assign \en$11  = en;
  assign w10 = \w$12 ;
  assign \clear$14  = 1'h0;
  assign \en$15  = en;
  assign w11 = \w$16 ;
  assign row0_in = x_in;
  assign x_out = \x_in$20 ;
  assign row1_in = \x_in$22 ;
  assign \x_out$25  = \x_in$24 ;
  assign acc = out00;
  assign \acc$29  = out01;
  assign \acc$31  = out10;
  assign \acc$33  = out11;
endmodule

(* src = "/tmp/ipykernel_3846/1200065306.py:15" *)
(* generator = "Amaranth" *)
module \tt_um_lacesse_npu.npu.array.mac00 (rst, w, x_in, en, x_out, acc, clk);
  reg \$auto$verilog_backend.cc:2355:dump_module$3  = 0;
  wire \$1 ;
  wire \$2 ;
  wire [16:0] \$3 ;
  wire [16:0] \$4 ;
  reg [7:0] \$5 ;
  reg [15:0] \$6 ;
  (* src = "/tmp/ipykernel_3846/1200065306.py:12" *)
  output [15:0] acc;
  reg [15:0] acc = 16'h0000;
  (* src = "/tmp/ipykernel_3846/1200065306.py:10" *)
  wire clear;
  (* src = "/tmp/ipykernel_3846/3191868895.py:21" *)
  input clk;
  wire clk;
  (* src = "/tmp/ipykernel_3846/1200065306.py:11" *)
  input en;
  wire en;
  (* src = "/tmp/ipykernel_3846/3191868895.py:21" *)
  input rst;
  wire rst;
  (* src = "/tmp/ipykernel_3846/1200065306.py:9" *)
  input [1:0] w;
  wire [1:0] w;
  (* src = "/tmp/ipykernel_3846/1200065306.py:7" *)
  input [7:0] x_in;
  wire [7:0] x_in;
  (* src = "/tmp/ipykernel_3846/1200065306.py:8" *)
  output [7:0] x_out;
  reg [7:0] x_out = 8'h00;
  assign \$4  = $signed(acc) - (* src = "/tmp/ipykernel_3846/1200065306.py:27" *) $signed(x_in);
  (* src = "/tmp/ipykernel_3846/1200065306.py:8" *)
  always @(posedge clk)
    x_out <= \$5 ;
  (* src = "/tmp/ipykernel_3846/1200065306.py:12" *)
  always @(posedge clk)
    acc <= \$6 ;
  assign \$1  = w == (* src = "/tmp/ipykernel_3846/1200065306.py:24" *) 1'h1;
  assign \$2  = w == (* src = "/tmp/ipykernel_3846/1200065306.py:26" *) 2'h3;
  assign \$3  = $signed(acc) + (* src = "/tmp/ipykernel_3846/1200065306.py:25" *) $signed(x_in);
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$3 ) begin end
    \$5  = x_in;
    if (rst) begin
      \$5  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$3 ) begin end
    \$6  = acc;
    casez ({ en, 1'h0 })
      2'b1?:
          if (\$1 ) begin
            \$6  = \$3 [15:0];
          end else if (\$2 ) begin
            \$6  = \$4 [15:0];
          end
    endcase
    if (rst) begin
      \$6  = 16'h0000;
    end
  end
  assign clear = 1'h0;
endmodule

(* src = "/tmp/ipykernel_3846/1200065306.py:15" *)
(* generator = "Amaranth" *)
module \tt_um_lacesse_npu.npu.array.mac01 (rst, w, en, x_in, acc, clk);
  reg \$auto$verilog_backend.cc:2355:dump_module$4  = 0;
  wire \$1 ;
  wire \$2 ;
  wire [16:0] \$3 ;
  wire [16:0] \$4 ;
  reg [7:0] \$5 ;
  reg [15:0] \$6 ;
  (* src = "/tmp/ipykernel_3846/1200065306.py:12" *)
  output [15:0] acc;
  reg [15:0] acc = 16'h0000;
  (* src = "/tmp/ipykernel_3846/1200065306.py:10" *)
  wire clear;
  (* src = "/tmp/ipykernel_3846/3191868895.py:21" *)
  input clk;
  wire clk;
  (* src = "/tmp/ipykernel_3846/1200065306.py:11" *)
  input en;
  wire en;
  (* src = "/tmp/ipykernel_3846/3191868895.py:21" *)
  input rst;
  wire rst;
  (* src = "/tmp/ipykernel_3846/1200065306.py:9" *)
  input [1:0] w;
  wire [1:0] w;
  (* src = "/tmp/ipykernel_3846/1200065306.py:7" *)
  input [7:0] x_in;
  wire [7:0] x_in;
  (* src = "/tmp/ipykernel_3846/1200065306.py:8" *)
  reg [7:0] x_out = 8'h00;
  assign \$4  = $signed(acc) - (* src = "/tmp/ipykernel_3846/1200065306.py:27" *) $signed(x_in);
  (* src = "/tmp/ipykernel_3846/1200065306.py:8" *)
  always @(posedge clk)
    x_out <= \$5 ;
  (* src = "/tmp/ipykernel_3846/1200065306.py:12" *)
  always @(posedge clk)
    acc <= \$6 ;
  assign \$1  = w == (* src = "/tmp/ipykernel_3846/1200065306.py:24" *) 1'h1;
  assign \$2  = w == (* src = "/tmp/ipykernel_3846/1200065306.py:26" *) 2'h3;
  assign \$3  = $signed(acc) + (* src = "/tmp/ipykernel_3846/1200065306.py:25" *) $signed(x_in);
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$4 ) begin end
    \$5  = x_in;
    if (rst) begin
      \$5  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$4 ) begin end
    \$6  = acc;
    casez ({ en, 1'h0 })
      2'b1?:
          if (\$1 ) begin
            \$6  = \$3 [15:0];
          end else if (\$2 ) begin
            \$6  = \$4 [15:0];
          end
    endcase
    if (rst) begin
      \$6  = 16'h0000;
    end
  end
  assign clear = 1'h0;
endmodule

(* src = "/tmp/ipykernel_3846/1200065306.py:15" *)
(* generator = "Amaranth" *)
module \tt_um_lacesse_npu.npu.array.mac10 (rst, w, x_in, en, x_out, acc, clk);
  reg \$auto$verilog_backend.cc:2355:dump_module$5  = 0;
  wire \$1 ;
  wire \$2 ;
  wire [16:0] \$3 ;
  wire [16:0] \$4 ;
  reg [7:0] \$5 ;
  reg [15:0] \$6 ;
  (* src = "/tmp/ipykernel_3846/1200065306.py:12" *)
  output [15:0] acc;
  reg [15:0] acc = 16'h0000;
  (* src = "/tmp/ipykernel_3846/1200065306.py:10" *)
  wire clear;
  (* src = "/tmp/ipykernel_3846/3191868895.py:21" *)
  input clk;
  wire clk;
  (* src = "/tmp/ipykernel_3846/1200065306.py:11" *)
  input en;
  wire en;
  (* src = "/tmp/ipykernel_3846/3191868895.py:21" *)
  input rst;
  wire rst;
  (* src = "/tmp/ipykernel_3846/1200065306.py:9" *)
  input [1:0] w;
  wire [1:0] w;
  (* src = "/tmp/ipykernel_3846/1200065306.py:7" *)
  input [7:0] x_in;
  wire [7:0] x_in;
  (* src = "/tmp/ipykernel_3846/1200065306.py:8" *)
  output [7:0] x_out;
  reg [7:0] x_out = 8'h00;
  assign \$4  = $signed(acc) - (* src = "/tmp/ipykernel_3846/1200065306.py:27" *) $signed(x_in);
  (* src = "/tmp/ipykernel_3846/1200065306.py:8" *)
  always @(posedge clk)
    x_out <= \$5 ;
  (* src = "/tmp/ipykernel_3846/1200065306.py:12" *)
  always @(posedge clk)
    acc <= \$6 ;
  assign \$1  = w == (* src = "/tmp/ipykernel_3846/1200065306.py:24" *) 1'h1;
  assign \$2  = w == (* src = "/tmp/ipykernel_3846/1200065306.py:26" *) 2'h3;
  assign \$3  = $signed(acc) + (* src = "/tmp/ipykernel_3846/1200065306.py:25" *) $signed(x_in);
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$5 ) begin end
    \$5  = x_in;
    if (rst) begin
      \$5  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$5 ) begin end
    \$6  = acc;
    casez ({ en, 1'h0 })
      2'b1?:
          if (\$1 ) begin
            \$6  = \$3 [15:0];
          end else if (\$2 ) begin
            \$6  = \$4 [15:0];
          end
    endcase
    if (rst) begin
      \$6  = 16'h0000;
    end
  end
  assign clear = 1'h0;
endmodule

(* src = "/tmp/ipykernel_3846/1200065306.py:15" *)
(* generator = "Amaranth" *)
module \tt_um_lacesse_npu.npu.array.mac11 (rst, w, en, x_in, acc, clk);
  reg \$auto$verilog_backend.cc:2355:dump_module$6  = 0;
  wire \$1 ;
  wire \$2 ;
  wire [16:0] \$3 ;
  wire [16:0] \$4 ;
  reg [7:0] \$5 ;
  reg [15:0] \$6 ;
  (* src = "/tmp/ipykernel_3846/1200065306.py:12" *)
  output [15:0] acc;
  reg [15:0] acc = 16'h0000;
  (* src = "/tmp/ipykernel_3846/1200065306.py:10" *)
  wire clear;
  (* src = "/tmp/ipykernel_3846/3191868895.py:21" *)
  input clk;
  wire clk;
  (* src = "/tmp/ipykernel_3846/1200065306.py:11" *)
  input en;
  wire en;
  (* src = "/tmp/ipykernel_3846/3191868895.py:21" *)
  input rst;
  wire rst;
  (* src = "/tmp/ipykernel_3846/1200065306.py:9" *)
  input [1:0] w;
  wire [1:0] w;
  (* src = "/tmp/ipykernel_3846/1200065306.py:7" *)
  input [7:0] x_in;
  wire [7:0] x_in;
  (* src = "/tmp/ipykernel_3846/1200065306.py:8" *)
  reg [7:0] x_out = 8'h00;
  assign \$4  = $signed(acc) - (* src = "/tmp/ipykernel_3846/1200065306.py:27" *) $signed(x_in);
  (* src = "/tmp/ipykernel_3846/1200065306.py:8" *)
  always @(posedge clk)
    x_out <= \$5 ;
  (* src = "/tmp/ipykernel_3846/1200065306.py:12" *)
  always @(posedge clk)
    acc <= \$6 ;
  assign \$1  = w == (* src = "/tmp/ipykernel_3846/1200065306.py:24" *) 1'h1;
  assign \$2  = w == (* src = "/tmp/ipykernel_3846/1200065306.py:26" *) 2'h3;
  assign \$3  = $signed(acc) + (* src = "/tmp/ipykernel_3846/1200065306.py:25" *) $signed(x_in);
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$6 ) begin end
    \$5  = x_in;
    if (rst) begin
      \$5  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$6 ) begin end
    \$6  = acc;
    casez ({ en, 1'h0 })
      2'b1?:
          if (\$1 ) begin
            \$6  = \$3 [15:0];
          end else if (\$2 ) begin
            \$6  = \$4 [15:0];
          end
    endcase
    if (rst) begin
      \$6  = 16'h0000;
    end
  end
  assign clear = 1'h0;
endmodule
