/* Generated by Amaranth Yosys 0.50 (PyPI ver 0.50.0.0.post122, git sha1 b5170e139) */

(* top =  1  *)
(* src = "/tmp/ipykernel_13211/1606921400.py:72" *)
(* generator = "Amaranth" *)
module tt_um_lacesse_npu(\$signal$2 , \$signal$5 , \$signal$6 , \$signal$7 , \$signal$1 , \$signal$3 , \$signal$4 , \$signal );
  reg \$auto$verilog_backend.cc:2355:dump_module$1  = 0;
  reg [31:0] \$1 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:67" *)
  input [7:0] \$signal ;
  wire [7:0] \$signal ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:67" *)
  output [7:0] \$signal$1 ;
  wire [7:0] \$signal$1 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:69" *)
  wire \$signal$11 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:44" *)
  wire \$signal$12 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:44" *)
  wire [9:0] \$signal$13 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:45" *)
  reg [31:0] \$signal$14  = 32'd0;
  (* src = "/tmp/ipykernel_13211/1606921400.py:67" *)
  wire [7:0] \$signal$16 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:46" *)
  wire [31:0] \$signal$17 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:68" *)
  wire [7:0] \$signal$18 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:68" *)
  wire [7:0] \$signal$19 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:68" *)
  input [7:0] \$signal$2 ;
  wire [7:0] \$signal$2 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:68" *)
  wire [7:0] \$signal$20 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:69" *)
  wire \$signal$21 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:68" *)
  output [7:0] \$signal$3 ;
  wire [7:0] \$signal$3 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:68" *)
  output [7:0] \$signal$4 ;
  wire [7:0] \$signal$4 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:69" *)
  input \$signal$5 ;
  wire \$signal$5 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:69" *)
  input \$signal$6 ;
  wire \$signal$6 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:69" *)
  input \$signal$7 ;
  wire \$signal$7 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:69" *)
  wire \$signal$9 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:73" *)
  wire clk;
  (* src = "/tmp/ipykernel_13211/1606921400.py:73" *)
  wire rst;
  (* init = 32'd0 *)
  (* src = "/tmp/ipykernel_13211/1606921400.py:76" *)
  wire [31:0] shift_reg;
  assign rst = ~ (* src = "/tmp/ipykernel_13211/1606921400.py:74" *) \$signal$7 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:76" *)
  always @(posedge \$signal$6 )
    \$signal$14  <= \$1 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:75" *)
  \tt_um_lacesse_npu.npu  npu (
    .clk(\$signal$6 ),
    .\port$0$3 (\$signal [3:1]),
    .\port$55$0 (\$signal$14 ),
    .\port$72$0 (\$signal$17 ),
    .rst(rst)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$1  = \$signal$14 ;
    if (\$signal [0]) begin
      \$1  = { \$signal$14 [27:0], \$signal [7:4] };
    end
    if (rst) begin
      \$1  = 32'd0;
    end
  end
  assign clk = \$signal$6 ;
  assign \$signal$9  = \$signal$6 ;
  assign \$signal$11  = \$signal$7 ;
  assign \$signal$12  = \$signal [1];
  assign \$signal$13  = { 8'h00, \$signal [3:2] };
  assign shift_reg = \$signal$14 ;
  assign \$signal$16  = \$signal$17 [7:0];
  assign \$signal$18  = 8'hff;
  assign \$signal$19  = 8'h00;
  assign \$signal$20  = \$signal$2 ;
  assign \$signal$21  = \$signal$5 ;
  assign \$signal$1  = \$signal$17 [7:0];
  assign \$signal$3  = 8'h00;
  assign \$signal$4  = 8'hff;
endmodule

(* src = "/tmp/ipykernel_13211/1606921400.py:49" *)
(* generator = "Amaranth" *)
module \tt_um_lacesse_npu.npu (clk, rst, \port$55$0 , \port$72$0 , \port$0$3 );
  reg \$auto$verilog_backend.cc:2355:dump_module$2  = 0;
  wire \$1 ;
  reg [31:0] \$10 ;
  wire \$2 ;
  wire \$3 ;
  wire \$4 ;
  reg \$5 ;
  reg [1:0] \$6 ;
  reg [1:0] \$7 ;
  reg [1:0] \$8 ;
  reg [1:0] \$9 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:22" *)
  reg [1:0] \$signal  = 2'h0;
  (* init = 2'h0 *)
  (* src = "/tmp/ipykernel_13211/1606921400.py:51" *)
  wire [1:0] \$signal$1 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:21" *)
  reg [7:0] \$signal$10 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:45" *)
  wire [31:0] \$signal$11 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:21" *)
  reg [7:0] \$signal$12 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:45" *)
  wire [31:0] \$signal$13 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:46" *)
  reg \$signal$17  = 1'h0;
  (* src = "/tmp/ipykernel_13211/1606921400.py:46" *)
  reg [31:0] \$signal$18  = 32'd0;
  (* src = "/tmp/ipykernel_13211/1606921400.py:22" *)
  reg [1:0] \$signal$2  = 2'h0;
  (* init = 2'h0 *)
  (* src = "/tmp/ipykernel_13211/1606921400.py:51" *)
  wire [1:0] \$signal$3 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:22" *)
  reg [1:0] \$signal$4  = 2'h0;
  (* init = 2'h0 *)
  (* src = "/tmp/ipykernel_13211/1606921400.py:51" *)
  wire [1:0] \$signal$5 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:22" *)
  reg [1:0] \$signal$6  = 2'h0;
  (* init = 2'h0 *)
  (* src = "/tmp/ipykernel_13211/1606921400.py:51" *)
  wire [1:0] \$signal$7 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:44" *)
  wire \$signal$8 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:44" *)
  wire [9:0] \$signal$9 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:73" *)
  input clk;
  wire clk;
  (* src = "/tmp/ipykernel_13211/1606921400.py:23" *)
  reg en;
  (* src = "/tmp/ipykernel_13211/1606921400.py:24" *)
  wire [15:0] out00;
  input [2:0] \port$0$3 ;
  wire [2:0] \port$0$3 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:45" *)
  input [31:0] \port$55$0 ;
  wire [31:0] \port$55$0 ;
  (* init = 32'd0 *)
  (* src = "/tmp/ipykernel_13211/1606921400.py:46" *)
  output [31:0] \port$72$0 ;
  wire [31:0] \port$72$0 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:73" *)
  input rst;
  wire rst;
  assign \$1  = \port$0$3 [2:1] == (* src = "/tmp/ipykernel_13211/1606921400.py:55" *) 1'h1;
  assign \$2  = \port$0$3 [2:1] == (* src = "/tmp/ipykernel_13211/1606921400.py:59" *) 2'h2;
  assign \$3  = \port$0$3 [2:1] == (* src = "/tmp/ipykernel_13211/1606921400.py:55" *) 1'h1;
  assign \$4  = \port$0$3 [2:1] == (* src = "/tmp/ipykernel_13211/1606921400.py:59" *) 2'h2;
  (* src = "/tmp/ipykernel_13211/1606921400.py:46" *)
  always @(posedge clk)
    \$signal$17  <= \$5 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:51" *)
  always @(posedge clk)
    \$signal  <= \$6 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:51" *)
  always @(posedge clk)
    \$signal$2  <= \$7 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:51" *)
  always @(posedge clk)
    \$signal$4  <= \$8 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:51" *)
  always @(posedge clk)
    \$signal$6  <= \$9 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:46" *)
  always @(posedge clk)
    \$signal$18  <= \$10 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:50" *)
  \tt_um_lacesse_npu.npu.array  array (
    .clk(clk),
    .en(en),
    .out00(out00),
    .\port$56$0 (\$signal$10 ),
    .\port$57$0 (\$signal$12 ),
    .rst(rst),
    .w(\$signal ),
    .\w$2 (\$signal$2 ),
    .\w$4 (\$signal$4 ),
    .\w$6 (\$signal$6 )
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    \$signal$10  = 8'h00;
    if (\port$0$3 [0]) begin
      if (\$1 ) begin
      end else if (\$2 ) begin
        \$signal$10  = \port$55$0 [7:0];
      end
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    \$signal$12  = 8'h00;
    if (\port$0$3 [0]) begin
      if (\$1 ) begin
      end else if (\$2 ) begin
        \$signal$12  = 8'h00;
      end
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    en = 1'h0;
    if (\port$0$3 [0]) begin
      if (\$1 ) begin
      end else if (\$2 ) begin
        en = 1'h1;
      end
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    \$5  = 1'h0;
    if (\port$0$3 [0]) begin
      if (\$3 ) begin
        \$5  = 1'h1;
      end else if (\$4 ) begin
        \$5  = 1'h1;
      end
    end
    if (rst) begin
      \$5  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    \$6  = \$signal ;
    if (\port$0$3 [0]) begin
      if (\$3 ) begin
        \$6  = \port$55$0 [1:0];
      end
    end
    if (rst) begin
      \$6  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    \$7  = \$signal$2 ;
    if (\port$0$3 [0]) begin
      if (\$3 ) begin
        \$7  = \port$55$0 [9:8];
      end
    end
    if (rst) begin
      \$7  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    \$8  = \$signal$4 ;
    if (\port$0$3 [0]) begin
      if (\$3 ) begin
        \$8  = \port$55$0 [17:16];
      end
    end
    if (rst) begin
      \$8  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    \$9  = \$signal$6 ;
    if (\port$0$3 [0]) begin
      if (\$3 ) begin
        \$9  = \port$55$0 [25:24];
      end
    end
    if (rst) begin
      \$9  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    \$10  = \$signal$18 ;
    if (\port$0$3 [0]) begin
      if (\$3 ) begin
        \$10  = 32'd0;
      end else if (\$4 ) begin
        \$10  = { out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00 };
      end
    end
    if (rst) begin
      \$10  = 32'd0;
    end
  end
  assign \$signal$1  = \$signal ;
  assign \$signal$3  = \$signal$2 ;
  assign \$signal$5  = \$signal$4 ;
  assign \$signal$7  = \$signal$6 ;
  assign \$signal$8  = \port$0$3 [0];
  assign \$signal$9  = { 8'h00, \port$0$3 [2:1] };
  assign \$signal$11  = \port$55$0 ;
  assign \$signal$13  = 32'd0;
  assign \port$72$0  = \$signal$18 ;
endmodule

(* src = "/tmp/ipykernel_13211/1606921400.py:27" *)
(* generator = "Amaranth" *)
module \tt_um_lacesse_npu.npu.array (rst, \port$56$0 , \port$57$0 , en, w, \w$2 , \w$4 , \w$6 , out00, clk);
  (* src = "/tmp/ipykernel_13211/1606921400.py:22" *)
  wire [1:0] \$signal ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:9" *)
  wire \$signal$10 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:9" *)
  wire \$signal$11 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:9" *)
  wire \$signal$12 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:7" *)
  wire [7:0] \$signal$13 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:21" *)
  wire [7:0] \$signal$14 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:7" *)
  wire [7:0] \$signal$15 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:7" *)
  wire [7:0] \$signal$16 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:7" *)
  wire [7:0] \$signal$17 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:21" *)
  wire [7:0] \$signal$18 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:7" *)
  wire [7:0] \$signal$19 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:7" *)
  wire [7:0] \$signal$20 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:9" *)
  wire [15:0] \$signal$22 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:22" *)
  wire [1:0] \$signal$3 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:22" *)
  wire [1:0] \$signal$5 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:22" *)
  wire [1:0] \$signal$7 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:9" *)
  wire \$signal$8 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:73" *)
  input clk;
  wire clk;
  (* src = "/tmp/ipykernel_13211/1606921400.py:9" *)
  input en;
  wire en;
  (* src = "/tmp/ipykernel_13211/1606921400.py:9" *)
  output [15:0] out00;
  wire [15:0] out00;
  (* src = "/tmp/ipykernel_13211/1606921400.py:21" *)
  input [7:0] \port$56$0 ;
  wire [7:0] \port$56$0 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:21" *)
  input [7:0] \port$57$0 ;
  wire [7:0] \port$57$0 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:73" *)
  input rst;
  wire rst;
  (* src = "/tmp/ipykernel_13211/1606921400.py:22" *)
  input [1:0] w;
  wire [1:0] w;
  (* src = "/tmp/ipykernel_13211/1606921400.py:22" *)
  input [1:0] \w$2 ;
  wire [1:0] \w$2 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:22" *)
  input [1:0] \w$4 ;
  wire [1:0] \w$4 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:22" *)
  input [1:0] \w$6 ;
  wire [1:0] \w$6 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:28" *)
  \tt_um_lacesse_npu.npu.array.mac00  mac00 (
    .clk(clk),
    .\port$56$0 (\port$56$0 ),
    .\port$58$0 (en),
    .\port$76$0 (\$signal$15 ),
    .\port$78$0 (out00),
    .rst(rst),
    .w(w)
  );
  (* src = "/tmp/ipykernel_13211/1606921400.py:29" *)
  \tt_um_lacesse_npu.npu.array.mac01  mac01 (
    .clk(clk),
    .\port$58$0 (en),
    .\port$76$0 (\$signal$15 ),
    .rst(rst),
    .w(\w$2 )
  );
  (* src = "/tmp/ipykernel_13211/1606921400.py:30" *)
  \tt_um_lacesse_npu.npu.array.mac10  mac10 (
    .clk(clk),
    .\port$57$0 (\port$57$0 ),
    .\port$58$0 (en),
    .\port$88$0 (\$signal$19 ),
    .rst(rst),
    .w(\w$4 )
  );
  (* src = "/tmp/ipykernel_13211/1606921400.py:31" *)
  \tt_um_lacesse_npu.npu.array.mac11  mac11 (
    .clk(clk),
    .\port$58$0 (en),
    .\port$88$0 (\$signal$19 ),
    .rst(rst),
    .w(\w$6 )
  );
  assign \$signal  = w;
  assign \$signal$3  = \w$2 ;
  assign \$signal$5  = \w$4 ;
  assign \$signal$7  = \w$6 ;
  assign \$signal$8  = en;
  assign \$signal$10  = en;
  assign \$signal$11  = en;
  assign \$signal$12  = en;
  assign \$signal$13  = \port$56$0 ;
  assign \$signal$14  = \port$56$0 ;
  assign \$signal$16  = \$signal$15 ;
  assign \$signal$17  = \port$57$0 ;
  assign \$signal$18  = \port$57$0 ;
  assign \$signal$20  = \$signal$19 ;
  assign \$signal$22  = out00;
endmodule

(* src = "/tmp/ipykernel_13211/1606921400.py:12" *)
(* generator = "Amaranth" *)
module \tt_um_lacesse_npu.npu.array.mac00 (rst, \port$56$0 , \port$58$0 , w, \port$76$0 , \port$78$0 , clk);
  reg \$auto$verilog_backend.cc:2355:dump_module$3  = 0;
  wire \$1 ;
  wire \$2 ;
  wire [16:0] \$3 ;
  wire [16:0] \$4 ;
  reg [7:0] \$5 ;
  reg [15:0] \$6 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:7" *)
  reg [7:0] \$signal  = 8'h00;
  (* src = "/tmp/ipykernel_13211/1606921400.py:7" *)
  wire [7:0] \$signal$3 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:9" *)
  wire \$signal$4 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:9" *)
  reg [15:0] \$signal$6  = 16'h0000;
  (* src = "/tmp/ipykernel_13211/1606921400.py:73" *)
  input clk;
  wire clk;
  (* src = "/tmp/ipykernel_13211/1606921400.py:7" *)
  input [7:0] \port$56$0 ;
  wire [7:0] \port$56$0 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:9" *)
  input \port$58$0 ;
  wire \port$58$0 ;
  (* init = 8'h00 *)
  (* src = "/tmp/ipykernel_13211/1606921400.py:7" *)
  output [7:0] \port$76$0 ;
  wire [7:0] \port$76$0 ;
  (* init = 16'h0000 *)
  (* src = "/tmp/ipykernel_13211/1606921400.py:9" *)
  output [15:0] \port$78$0 ;
  wire [15:0] \port$78$0 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:73" *)
  input rst;
  wire rst;
  (* src = "/tmp/ipykernel_13211/1606921400.py:8" *)
  input [1:0] w;
  wire [1:0] w;
  assign \$4  = $signed(\$signal$6 ) - (* src = "/tmp/ipykernel_13211/1606921400.py:16" *) $signed(\port$56$0 );
  (* src = "/tmp/ipykernel_13211/1606921400.py:7" *)
  always @(posedge clk)
    \$signal  <= \$5 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:9" *)
  always @(posedge clk)
    \$signal$6  <= \$6 ;
  assign \$1  = w == (* src = "/tmp/ipykernel_13211/1606921400.py:15" *) 1'h1;
  assign \$2  = w == (* src = "/tmp/ipykernel_13211/1606921400.py:16" *) 2'h3;
  assign \$3  = $signed(\$signal$6 ) + (* src = "/tmp/ipykernel_13211/1606921400.py:15" *) $signed(\port$56$0 );
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$3 ) begin end
    \$5  = \port$56$0 ;
    if (rst) begin
      \$5  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$3 ) begin end
    \$6  = \$signal$6 ;
    if (\port$58$0 ) begin
      if (\$1 ) begin
        \$6  = \$3 [15:0];
      end else if (\$2 ) begin
        \$6  = \$4 [15:0];
      end
    end
    if (rst) begin
      \$6  = 16'h0000;
    end
  end
  assign \$signal$3  = \port$56$0 ;
  assign \$signal$4  = \port$58$0 ;
  assign \port$76$0  = \$signal ;
  assign \port$78$0  = \$signal$6 ;
endmodule

(* src = "/tmp/ipykernel_13211/1606921400.py:12" *)
(* generator = "Amaranth" *)
module \tt_um_lacesse_npu.npu.array.mac01 (rst, \port$58$0 , w, \port$76$0 , clk);
  reg \$auto$verilog_backend.cc:2355:dump_module$4  = 0;
  wire \$1 ;
  wire \$2 ;
  wire [16:0] \$3 ;
  wire [16:0] \$4 ;
  reg [7:0] \$5 ;
  reg [15:0] \$6 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:7" *)
  reg [7:0] \$signal  = 8'h00;
  (* src = "/tmp/ipykernel_13211/1606921400.py:7" *)
  wire [7:0] \$signal$3 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:9" *)
  wire \$signal$4 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:9" *)
  reg [15:0] \$signal$6  = 16'h0000;
  (* src = "/tmp/ipykernel_13211/1606921400.py:73" *)
  input clk;
  wire clk;
  (* src = "/tmp/ipykernel_13211/1606921400.py:9" *)
  input \port$58$0 ;
  wire \port$58$0 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:7" *)
  input [7:0] \port$76$0 ;
  wire [7:0] \port$76$0 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:73" *)
  input rst;
  wire rst;
  (* src = "/tmp/ipykernel_13211/1606921400.py:8" *)
  input [1:0] w;
  wire [1:0] w;
  assign \$4  = $signed(\$signal$6 ) - (* src = "/tmp/ipykernel_13211/1606921400.py:16" *) $signed(\port$76$0 );
  (* src = "/tmp/ipykernel_13211/1606921400.py:7" *)
  always @(posedge clk)
    \$signal  <= \$5 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:9" *)
  always @(posedge clk)
    \$signal$6  <= \$6 ;
  assign \$1  = w == (* src = "/tmp/ipykernel_13211/1606921400.py:15" *) 1'h1;
  assign \$2  = w == (* src = "/tmp/ipykernel_13211/1606921400.py:16" *) 2'h3;
  assign \$3  = $signed(\$signal$6 ) + (* src = "/tmp/ipykernel_13211/1606921400.py:15" *) $signed(\port$76$0 );
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$4 ) begin end
    \$5  = \port$76$0 ;
    if (rst) begin
      \$5  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$4 ) begin end
    \$6  = \$signal$6 ;
    if (\port$58$0 ) begin
      if (\$1 ) begin
        \$6  = \$3 [15:0];
      end else if (\$2 ) begin
        \$6  = \$4 [15:0];
      end
    end
    if (rst) begin
      \$6  = 16'h0000;
    end
  end
  assign \$signal$3  = \port$76$0 ;
  assign \$signal$4  = \port$58$0 ;
endmodule

(* src = "/tmp/ipykernel_13211/1606921400.py:12" *)
(* generator = "Amaranth" *)
module \tt_um_lacesse_npu.npu.array.mac10 (rst, \port$57$0 , \port$58$0 , w, \port$88$0 , clk);
  reg \$auto$verilog_backend.cc:2355:dump_module$5  = 0;
  wire \$1 ;
  wire \$2 ;
  wire [16:0] \$3 ;
  wire [16:0] \$4 ;
  reg [7:0] \$5 ;
  reg [15:0] \$6 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:7" *)
  reg [7:0] \$signal  = 8'h00;
  (* src = "/tmp/ipykernel_13211/1606921400.py:7" *)
  wire [7:0] \$signal$3 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:9" *)
  wire \$signal$4 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:9" *)
  reg [15:0] \$signal$6  = 16'h0000;
  (* src = "/tmp/ipykernel_13211/1606921400.py:73" *)
  input clk;
  wire clk;
  (* src = "/tmp/ipykernel_13211/1606921400.py:7" *)
  input [7:0] \port$57$0 ;
  wire [7:0] \port$57$0 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:9" *)
  input \port$58$0 ;
  wire \port$58$0 ;
  (* init = 8'h00 *)
  (* src = "/tmp/ipykernel_13211/1606921400.py:7" *)
  output [7:0] \port$88$0 ;
  wire [7:0] \port$88$0 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:73" *)
  input rst;
  wire rst;
  (* src = "/tmp/ipykernel_13211/1606921400.py:8" *)
  input [1:0] w;
  wire [1:0] w;
  assign \$4  = $signed(\$signal$6 ) - (* src = "/tmp/ipykernel_13211/1606921400.py:16" *) $signed(\port$57$0 );
  (* src = "/tmp/ipykernel_13211/1606921400.py:7" *)
  always @(posedge clk)
    \$signal  <= \$5 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:9" *)
  always @(posedge clk)
    \$signal$6  <= \$6 ;
  assign \$1  = w == (* src = "/tmp/ipykernel_13211/1606921400.py:15" *) 1'h1;
  assign \$2  = w == (* src = "/tmp/ipykernel_13211/1606921400.py:16" *) 2'h3;
  assign \$3  = $signed(\$signal$6 ) + (* src = "/tmp/ipykernel_13211/1606921400.py:15" *) $signed(\port$57$0 );
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$5 ) begin end
    \$5  = \port$57$0 ;
    if (rst) begin
      \$5  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$5 ) begin end
    \$6  = \$signal$6 ;
    if (\port$58$0 ) begin
      if (\$1 ) begin
        \$6  = \$3 [15:0];
      end else if (\$2 ) begin
        \$6  = \$4 [15:0];
      end
    end
    if (rst) begin
      \$6  = 16'h0000;
    end
  end
  assign \$signal$3  = \port$57$0 ;
  assign \$signal$4  = \port$58$0 ;
  assign \port$88$0  = \$signal ;
endmodule

(* src = "/tmp/ipykernel_13211/1606921400.py:12" *)
(* generator = "Amaranth" *)
module \tt_um_lacesse_npu.npu.array.mac11 (rst, \port$58$0 , w, \port$88$0 , clk);
  reg \$auto$verilog_backend.cc:2355:dump_module$6  = 0;
  wire \$1 ;
  wire \$2 ;
  wire [16:0] \$3 ;
  wire [16:0] \$4 ;
  reg [7:0] \$5 ;
  reg [15:0] \$6 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:7" *)
  reg [7:0] \$signal  = 8'h00;
  (* src = "/tmp/ipykernel_13211/1606921400.py:7" *)
  wire [7:0] \$signal$3 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:9" *)
  wire \$signal$4 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:9" *)
  reg [15:0] \$signal$6  = 16'h0000;
  (* src = "/tmp/ipykernel_13211/1606921400.py:73" *)
  input clk;
  wire clk;
  (* src = "/tmp/ipykernel_13211/1606921400.py:9" *)
  input \port$58$0 ;
  wire \port$58$0 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:7" *)
  input [7:0] \port$88$0 ;
  wire [7:0] \port$88$0 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:73" *)
  input rst;
  wire rst;
  (* src = "/tmp/ipykernel_13211/1606921400.py:8" *)
  input [1:0] w;
  wire [1:0] w;
  assign \$4  = $signed(\$signal$6 ) - (* src = "/tmp/ipykernel_13211/1606921400.py:16" *) $signed(\port$88$0 );
  (* src = "/tmp/ipykernel_13211/1606921400.py:7" *)
  always @(posedge clk)
    \$signal  <= \$5 ;
  (* src = "/tmp/ipykernel_13211/1606921400.py:9" *)
  always @(posedge clk)
    \$signal$6  <= \$6 ;
  assign \$1  = w == (* src = "/tmp/ipykernel_13211/1606921400.py:15" *) 1'h1;
  assign \$2  = w == (* src = "/tmp/ipykernel_13211/1606921400.py:16" *) 2'h3;
  assign \$3  = $signed(\$signal$6 ) + (* src = "/tmp/ipykernel_13211/1606921400.py:15" *) $signed(\port$88$0 );
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$6 ) begin end
    \$5  = \port$88$0 ;
    if (rst) begin
      \$5  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$6 ) begin end
    \$6  = \$signal$6 ;
    if (\port$58$0 ) begin
      if (\$1 ) begin
        \$6  = \$3 [15:0];
      end else if (\$2 ) begin
        \$6  = \$4 [15:0];
      end
    end
    if (rst) begin
      \$6  = 16'h0000;
    end
  end
  assign \$signal$3  = \port$88$0 ;
  assign \$signal$4  = \port$58$0 ;
endmodule
