/* Generated by Amaranth Yosys 0.50 (PyPI ver 0.50.0.0.post122, git sha1 b5170e139) */

(* top =  1  *)
(* src = "/tmp/ipykernel_13211/2392253499.py:46" *)
(* generator = "Amaranth" *)
module tt_um_lacesse_npu(\$signal$2 , \$signal$5 , \$signal$6 , \$signal$7 , \$signal$1 , \$signal$3 , \$signal$4 , \$signal );
  reg \$auto$verilog_backend.cc:2355:dump_module$1  = 0;
  reg [31:0] \$1 ;
  (* src = "/tmp/ipykernel_13211/2392253499.py:41" *)
  input [7:0] \$signal ;
  wire [7:0] \$signal ;
  (* src = "/tmp/ipykernel_13211/2392253499.py:41" *)
  output [7:0] \$signal$1 ;
  wire [7:0] \$signal$1 ;
  (* src = "/tmp/ipykernel_13211/2392253499.py:43" *)
  wire \$signal$11 ;
  (* src = "/tmp/ipykernel_13211/2392253499.py:7" *)
  wire \$signal$12 ;
  (* src = "/tmp/ipykernel_13211/2392253499.py:7" *)
  wire [9:0] \$signal$13 ;
  (* src = "/tmp/ipykernel_13211/2392253499.py:8" *)
  reg [31:0] \$signal$14  = 32'd0;
  (* src = "/tmp/ipykernel_13211/2392253499.py:41" *)
  wire [7:0] \$signal$16 ;
  (* src = "/tmp/ipykernel_13211/2392253499.py:9" *)
  wire [31:0] \$signal$17 ;
  (* src = "/tmp/ipykernel_13211/2392253499.py:42" *)
  wire [7:0] \$signal$18 ;
  (* src = "/tmp/ipykernel_13211/2392253499.py:42" *)
  wire [7:0] \$signal$19 ;
  (* src = "/tmp/ipykernel_13211/2392253499.py:42" *)
  input [7:0] \$signal$2 ;
  wire [7:0] \$signal$2 ;
  (* src = "/tmp/ipykernel_13211/2392253499.py:42" *)
  wire [7:0] \$signal$20 ;
  (* src = "/tmp/ipykernel_13211/2392253499.py:43" *)
  wire \$signal$21 ;
  (* src = "/tmp/ipykernel_13211/2392253499.py:42" *)
  output [7:0] \$signal$3 ;
  wire [7:0] \$signal$3 ;
  (* src = "/tmp/ipykernel_13211/2392253499.py:42" *)
  output [7:0] \$signal$4 ;
  wire [7:0] \$signal$4 ;
  (* src = "/tmp/ipykernel_13211/2392253499.py:43" *)
  input \$signal$5 ;
  wire \$signal$5 ;
  (* src = "/tmp/ipykernel_13211/2392253499.py:43" *)
  input \$signal$6 ;
  wire \$signal$6 ;
  (* src = "/tmp/ipykernel_13211/2392253499.py:43" *)
  input \$signal$7 ;
  wire \$signal$7 ;
  (* src = "/tmp/ipykernel_13211/2392253499.py:43" *)
  wire \$signal$9 ;
  (* src = "/tmp/ipykernel_13211/2392253499.py:48" *)
  wire clk;
  (* src = "/tmp/ipykernel_13211/2392253499.py:48" *)
  wire rst;
  (* init = 32'd0 *)
  (* src = "/tmp/ipykernel_13211/2392253499.py:52" *)
  wire [31:0] shift_reg;
  assign rst = ~ (* src = "/tmp/ipykernel_13211/2392253499.py:49" *) \$signal$7 ;
  (* src = "/tmp/ipykernel_13211/2392253499.py:52" *)
  always @(posedge \$signal$6 )
    \$signal$14  <= \$1 ;
  (* src = "/tmp/ipykernel_13211/2392253499.py:51" *)
  \tt_um_lacesse_npu.npu  npu (
    .clk(\$signal$6 ),
    .\port$0$3 (\$signal [3:1]),
    .\port$59$0 (\$signal$14 ),
    .\port$76$0 (\$signal$17 ),
    .rst(rst)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$1  = \$signal$14 ;
    if (\$signal [0]) begin
      \$1  = { \$signal$14 [27:0], \$signal [7:4] };
    end
    if (rst) begin
      \$1  = 32'd0;
    end
  end
  assign clk = \$signal$6 ;
  assign \$signal$9  = \$signal$6 ;
  assign \$signal$11  = \$signal$7 ;
  assign \$signal$12  = \$signal [1];
  assign \$signal$13  = { 8'h00, \$signal [3:2] };
  assign shift_reg = \$signal$14 ;
  assign \$signal$16  = \$signal$17 [7:0];
  assign \$signal$18  = 8'hff;
  assign \$signal$19  = 8'h00;
  assign \$signal$20  = \$signal$2 ;
  assign \$signal$21  = \$signal$5 ;
  assign \$signal$1  = \$signal$17 [7:0];
  assign \$signal$3  = 8'h00;
  assign \$signal$4  = 8'hff;
endmodule

(* src = "/tmp/ipykernel_13211/2392253499.py:12" *)
(* generator = "Amaranth" *)
module \tt_um_lacesse_npu.npu (clk, rst, \port$59$0 , \port$76$0 , \port$0$3 );
  reg \$auto$verilog_backend.cc:2355:dump_module$2  = 0;
  wire \$1 ;
  reg [31:0] \$10 ;
  wire \$2 ;
  wire \$3 ;
  wire \$4 ;
  reg \$5 ;
  reg [1:0] \$6 ;
  reg [1:0] \$7 ;
  reg [1:0] \$8 ;
  reg [1:0] \$9 ;
  (* src = "/tmp/ipykernel_13211/2392253499.py:7" *)
  wire \$signal ;
  (* src = "/tmp/ipykernel_13211/2392253499.py:8" *)
  wire [31:0] \$signal$11 ;
  (* src = "/tmp/ipykernel_13211/2392253499.py:8" *)
  wire [31:0] \$signal$13 ;
  (* src = "/tmp/ipykernel_13211/2392253499.py:9" *)
  reg \$signal$17  = 1'h0;
  (* src = "/tmp/ipykernel_13211/2392253499.py:9" *)
  reg [31:0] \$signal$18  = 32'd0;
  (* src = "/tmp/ipykernel_13211/2392253499.py:7" *)
  wire [9:0] \$signal$9 ;
  (* src = "/tmp/ipykernel_13211/2392253499.py:48" *)
  input clk;
  wire clk;
  (* src = "/tmp/ipykernel_13211/1200065306.py:45" *)
  reg en;
  (* src = "/tmp/ipykernel_13211/1200065306.py:48" *)
  wire [15:0] out00;
  input [2:0] \port$0$3 ;
  wire [2:0] \port$0$3 ;
  (* src = "/tmp/ipykernel_13211/2392253499.py:8" *)
  input [31:0] \port$59$0 ;
  wire [31:0] \port$59$0 ;
  (* init = 32'd0 *)
  (* src = "/tmp/ipykernel_13211/2392253499.py:9" *)
  output [31:0] \port$76$0 ;
  wire [31:0] \port$76$0 ;
  (* src = "/tmp/ipykernel_13211/1200065306.py:35" *)
  reg [7:0] row0_in;
  (* src = "/tmp/ipykernel_13211/1200065306.py:36" *)
  reg [7:0] row1_in;
  (* src = "/tmp/ipykernel_13211/2392253499.py:48" *)
  input rst;
  wire rst;
  (* src = "/tmp/ipykernel_13211/1200065306.py:39" *)
  reg [1:0] w00 = 2'h0;
  (* init = 2'h0 *)
  (* src = "/tmp/ipykernel_13211/2392253499.py:16" *)
  wire [1:0] w00_reg;
  (* src = "/tmp/ipykernel_13211/1200065306.py:40" *)
  reg [1:0] w01 = 2'h0;
  (* init = 2'h0 *)
  (* src = "/tmp/ipykernel_13211/2392253499.py:16" *)
  wire [1:0] w01_reg;
  (* src = "/tmp/ipykernel_13211/1200065306.py:41" *)
  reg [1:0] w10 = 2'h0;
  (* init = 2'h0 *)
  (* src = "/tmp/ipykernel_13211/2392253499.py:17" *)
  wire [1:0] w10_reg;
  (* src = "/tmp/ipykernel_13211/1200065306.py:42" *)
  reg [1:0] w11 = 2'h0;
  (* init = 2'h0 *)
  (* src = "/tmp/ipykernel_13211/2392253499.py:17" *)
  wire [1:0] w11_reg;
  assign \$1  = \port$0$3 [2:1] == (* src = "/tmp/ipykernel_13211/2392253499.py:27" *) 1'h1;
  assign \$2  = \port$0$3 [2:1] == (* src = "/tmp/ipykernel_13211/2392253499.py:33" *) 2'h2;
  assign \$3  = \port$0$3 [2:1] == (* src = "/tmp/ipykernel_13211/2392253499.py:27" *) 1'h1;
  assign \$4  = \port$0$3 [2:1] == (* src = "/tmp/ipykernel_13211/2392253499.py:33" *) 2'h2;
  (* src = "/tmp/ipykernel_13211/2392253499.py:9" *)
  always @(posedge clk)
    \$signal$17  <= \$5 ;
  (* src = "/tmp/ipykernel_13211/2392253499.py:16" *)
  always @(posedge clk)
    w00 <= \$6 ;
  (* src = "/tmp/ipykernel_13211/2392253499.py:16" *)
  always @(posedge clk)
    w01 <= \$7 ;
  (* src = "/tmp/ipykernel_13211/2392253499.py:17" *)
  always @(posedge clk)
    w10 <= \$8 ;
  (* src = "/tmp/ipykernel_13211/2392253499.py:17" *)
  always @(posedge clk)
    w11 <= \$9 ;
  (* src = "/tmp/ipykernel_13211/2392253499.py:9" *)
  always @(posedge clk)
    \$signal$18  <= \$10 ;
  (* src = "/tmp/ipykernel_13211/2392253499.py:13" *)
  \tt_um_lacesse_npu.npu.array  array (
    .clk(clk),
    .en(en),
    .out00(out00),
    .rst(rst),
    .w(w00),
    .\w$12 (w10),
    .\w$16 (w11),
    .\w$8 (w01),
    .x_in(row0_in),
    .\x_in$22 (row1_in)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    row0_in = 8'h00;
    if (\port$0$3 [0]) begin
      if (\$1 ) begin
      end else if (\$2 ) begin
        row0_in = \port$59$0 [7:0];
      end
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    row1_in = 8'h00;
    if (\port$0$3 [0]) begin
      if (\$1 ) begin
      end else if (\$2 ) begin
        row1_in = 8'h00;
      end
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    en = 1'h0;
    if (\port$0$3 [0]) begin
      if (\$1 ) begin
      end else if (\$2 ) begin
        en = 1'h1;
      end
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    \$5  = 1'h0;
    if (\port$0$3 [0]) begin
      if (\$3 ) begin
        \$5  = 1'h1;
      end else if (\$4 ) begin
        \$5  = 1'h1;
      end
    end
    if (rst) begin
      \$5  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    \$6  = w00;
    if (\port$0$3 [0]) begin
      if (\$3 ) begin
        \$6  = \port$59$0 [1:0];
      end
    end
    if (rst) begin
      \$6  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    \$7  = w01;
    if (\port$0$3 [0]) begin
      if (\$3 ) begin
        \$7  = \port$59$0 [9:8];
      end
    end
    if (rst) begin
      \$7  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    \$8  = w10;
    if (\port$0$3 [0]) begin
      if (\$3 ) begin
        \$8  = \port$59$0 [17:16];
      end
    end
    if (rst) begin
      \$8  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    \$9  = w11;
    if (\port$0$3 [0]) begin
      if (\$3 ) begin
        \$9  = \port$59$0 [25:24];
      end
    end
    if (rst) begin
      \$9  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    \$10  = \$signal$18 ;
    if (\port$0$3 [0]) begin
      if (\$3 ) begin
        \$10  = 32'd0;
      end else if (\$4 ) begin
        \$10  = { out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00[15], out00 };
      end
    end
    if (rst) begin
      \$10  = 32'd0;
    end
  end
  assign w00_reg = w00;
  assign w01_reg = w01;
  assign w10_reg = w10;
  assign w11_reg = w11;
  assign \$signal  = \port$0$3 [0];
  assign \$signal$9  = { 8'h00, \port$0$3 [2:1] };
  assign \$signal$11  = \port$59$0 ;
  assign \$signal$13  = 32'd0;
  assign \port$76$0  = \$signal$18 ;
endmodule

(* src = "/tmp/ipykernel_13211/1200065306.py:54" *)
(* generator = "Amaranth" *)
module \tt_um_lacesse_npu.npu.array (rst, x_in, \x_in$22 , en, w, \w$8 , \w$12 , \w$16 , out00, clk);
  (* src = "/tmp/ipykernel_13211/1200065306.py:12" *)
  wire [15:0] acc;
  (* src = "/tmp/ipykernel_13211/1200065306.py:12" *)
  wire [15:0] \acc$29 ;
  (* src = "/tmp/ipykernel_13211/1200065306.py:12" *)
  wire [15:0] \acc$31 ;
  (* src = "/tmp/ipykernel_13211/1200065306.py:12" *)
  wire [15:0] \acc$33 ;
  (* src = "/tmp/ipykernel_13211/1200065306.py:10" *)
  wire clear;
  (* src = "/tmp/ipykernel_13211/1200065306.py:44" *)
  wire \clear$1 ;
  (* src = "/tmp/ipykernel_13211/1200065306.py:10" *)
  wire \clear$10 ;
  (* src = "/tmp/ipykernel_13211/1200065306.py:10" *)
  wire \clear$14 ;
  (* src = "/tmp/ipykernel_13211/1200065306.py:10" *)
  wire \clear$6 ;
  (* src = "/tmp/ipykernel_13211/2392253499.py:48" *)
  input clk;
  wire clk;
  (* src = "/tmp/ipykernel_13211/1200065306.py:11" *)
  input en;
  wire en;
  (* src = "/tmp/ipykernel_13211/1200065306.py:11" *)
  wire \en$11 ;
  (* src = "/tmp/ipykernel_13211/1200065306.py:11" *)
  wire \en$15 ;
  (* src = "/tmp/ipykernel_13211/1200065306.py:45" *)
  wire \en$3 ;
  (* src = "/tmp/ipykernel_13211/1200065306.py:11" *)
  wire \en$7 ;
  (* src = "/tmp/ipykernel_13211/1200065306.py:12" *)
  output [15:0] out00;
  wire [15:0] out00;
  (* src = "/tmp/ipykernel_13211/1200065306.py:49" *)
  wire [15:0] out01;
  (* src = "/tmp/ipykernel_13211/1200065306.py:50" *)
  wire [15:0] out10;
  (* src = "/tmp/ipykernel_13211/1200065306.py:51" *)
  wire [15:0] out11;
  (* src = "/tmp/ipykernel_13211/1200065306.py:35" *)
  wire [7:0] row0_in;
  (* src = "/tmp/ipykernel_13211/1200065306.py:36" *)
  wire [7:0] row1_in;
  (* src = "/tmp/ipykernel_13211/2392253499.py:48" *)
  input rst;
  wire rst;
  (* src = "/tmp/ipykernel_13211/1200065306.py:39" *)
  input [1:0] w;
  wire [1:0] w;
  (* src = "/tmp/ipykernel_13211/1200065306.py:41" *)
  input [1:0] \w$12 ;
  wire [1:0] \w$12 ;
  (* src = "/tmp/ipykernel_13211/1200065306.py:42" *)
  input [1:0] \w$16 ;
  wire [1:0] \w$16 ;
  (* src = "/tmp/ipykernel_13211/1200065306.py:40" *)
  input [1:0] \w$8 ;
  wire [1:0] \w$8 ;
  (* src = "/tmp/ipykernel_13211/1200065306.py:39" *)
  wire [1:0] w00;
  (* src = "/tmp/ipykernel_13211/1200065306.py:40" *)
  wire [1:0] w01;
  (* src = "/tmp/ipykernel_13211/1200065306.py:41" *)
  wire [1:0] w10;
  (* src = "/tmp/ipykernel_13211/1200065306.py:42" *)
  wire [1:0] w11;
  (* src = "/tmp/ipykernel_13211/1200065306.py:35" *)
  input [7:0] x_in;
  wire [7:0] x_in;
  (* src = "/tmp/ipykernel_13211/1200065306.py:7" *)
  wire [7:0] \x_in$20 ;
  (* src = "/tmp/ipykernel_13211/1200065306.py:36" *)
  input [7:0] \x_in$22 ;
  wire [7:0] \x_in$22 ;
  (* src = "/tmp/ipykernel_13211/1200065306.py:7" *)
  wire [7:0] \x_in$24 ;
  (* src = "/tmp/ipykernel_13211/1200065306.py:8" *)
  wire [7:0] x_out;
  (* src = "/tmp/ipykernel_13211/1200065306.py:8" *)
  wire [7:0] \x_out$25 ;
  (* src = "/tmp/ipykernel_13211/1200065306.py:57" *)
  \tt_um_lacesse_npu.npu.array.mac00  mac00 (
    .acc(out00),
    .clk(clk),
    .en(en),
    .rst(rst),
    .w(w),
    .x_in(x_in),
    .x_out(\x_in$20 )
  );
  (* src = "/tmp/ipykernel_13211/1200065306.py:58" *)
  \tt_um_lacesse_npu.npu.array.mac01  mac01 (
    .acc(out01),
    .clk(clk),
    .en(en),
    .rst(rst),
    .w(\w$8 ),
    .x_in(\x_in$20 )
  );
  (* src = "/tmp/ipykernel_13211/1200065306.py:59" *)
  \tt_um_lacesse_npu.npu.array.mac10  mac10 (
    .acc(out10),
    .clk(clk),
    .en(en),
    .rst(rst),
    .w(\w$12 ),
    .x_in(\x_in$22 ),
    .x_out(\x_in$24 )
  );
  (* src = "/tmp/ipykernel_13211/1200065306.py:60" *)
  \tt_um_lacesse_npu.npu.array.mac11  mac11 (
    .acc(out11),
    .clk(clk),
    .en(en),
    .rst(rst),
    .w(\w$16 ),
    .x_in(\x_in$24 )
  );
  assign clear = 1'h0;
  assign \clear$1  = 1'h0;
  assign \en$3  = en;
  assign w00 = w;
  assign \clear$6  = 1'h0;
  assign \en$7  = en;
  assign w01 = \w$8 ;
  assign \clear$10  = 1'h0;
  assign \en$11  = en;
  assign w10 = \w$12 ;
  assign \clear$14  = 1'h0;
  assign \en$15  = en;
  assign w11 = \w$16 ;
  assign row0_in = x_in;
  assign x_out = \x_in$20 ;
  assign row1_in = \x_in$22 ;
  assign \x_out$25  = \x_in$24 ;
  assign acc = out00;
  assign \acc$29  = out01;
  assign \acc$31  = out10;
  assign \acc$33  = out11;
endmodule

(* src = "/tmp/ipykernel_13211/1200065306.py:15" *)
(* generator = "Amaranth" *)
module \tt_um_lacesse_npu.npu.array.mac00 (rst, x_in, en, w, x_out, acc, clk);
  reg \$auto$verilog_backend.cc:2355:dump_module$3  = 0;
  wire \$1 ;
  wire \$2 ;
  wire [16:0] \$3 ;
  wire [16:0] \$4 ;
  reg [7:0] \$5 ;
  reg [15:0] \$6 ;
  (* src = "/tmp/ipykernel_13211/1200065306.py:12" *)
  output [15:0] acc;
  reg [15:0] acc = 16'h0000;
  (* src = "/tmp/ipykernel_13211/1200065306.py:10" *)
  wire clear;
  (* src = "/tmp/ipykernel_13211/2392253499.py:48" *)
  input clk;
  wire clk;
  (* src = "/tmp/ipykernel_13211/1200065306.py:11" *)
  input en;
  wire en;
  (* src = "/tmp/ipykernel_13211/2392253499.py:48" *)
  input rst;
  wire rst;
  (* src = "/tmp/ipykernel_13211/1200065306.py:9" *)
  input [1:0] w;
  wire [1:0] w;
  (* src = "/tmp/ipykernel_13211/1200065306.py:7" *)
  input [7:0] x_in;
  wire [7:0] x_in;
  (* src = "/tmp/ipykernel_13211/1200065306.py:8" *)
  output [7:0] x_out;
  reg [7:0] x_out = 8'h00;
  assign \$4  = $signed(acc) - (* src = "/tmp/ipykernel_13211/1200065306.py:27" *) $signed(x_in);
  (* src = "/tmp/ipykernel_13211/1200065306.py:8" *)
  always @(posedge clk)
    x_out <= \$5 ;
  (* src = "/tmp/ipykernel_13211/1200065306.py:12" *)
  always @(posedge clk)
    acc <= \$6 ;
  assign \$1  = w == (* src = "/tmp/ipykernel_13211/1200065306.py:24" *) 1'h1;
  assign \$2  = w == (* src = "/tmp/ipykernel_13211/1200065306.py:26" *) 2'h3;
  assign \$3  = $signed(acc) + (* src = "/tmp/ipykernel_13211/1200065306.py:25" *) $signed(x_in);
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$3 ) begin end
    \$5  = x_in;
    if (rst) begin
      \$5  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$3 ) begin end
    \$6  = acc;
    casez ({ en, 1'h0 })
      2'b1?:
          if (\$1 ) begin
            \$6  = \$3 [15:0];
          end else if (\$2 ) begin
            \$6  = \$4 [15:0];
          end
    endcase
    if (rst) begin
      \$6  = 16'h0000;
    end
  end
  assign clear = 1'h0;
endmodule

(* src = "/tmp/ipykernel_13211/1200065306.py:15" *)
(* generator = "Amaranth" *)
module \tt_um_lacesse_npu.npu.array.mac01 (rst, en, w, x_in, acc, clk);
  reg \$auto$verilog_backend.cc:2355:dump_module$4  = 0;
  wire \$1 ;
  wire \$2 ;
  wire [16:0] \$3 ;
  wire [16:0] \$4 ;
  reg [7:0] \$5 ;
  reg [15:0] \$6 ;
  (* src = "/tmp/ipykernel_13211/1200065306.py:12" *)
  output [15:0] acc;
  reg [15:0] acc = 16'h0000;
  (* src = "/tmp/ipykernel_13211/1200065306.py:10" *)
  wire clear;
  (* src = "/tmp/ipykernel_13211/2392253499.py:48" *)
  input clk;
  wire clk;
  (* src = "/tmp/ipykernel_13211/1200065306.py:11" *)
  input en;
  wire en;
  (* src = "/tmp/ipykernel_13211/2392253499.py:48" *)
  input rst;
  wire rst;
  (* src = "/tmp/ipykernel_13211/1200065306.py:9" *)
  input [1:0] w;
  wire [1:0] w;
  (* src = "/tmp/ipykernel_13211/1200065306.py:7" *)
  input [7:0] x_in;
  wire [7:0] x_in;
  (* src = "/tmp/ipykernel_13211/1200065306.py:8" *)
  reg [7:0] x_out = 8'h00;
  assign \$4  = $signed(acc) - (* src = "/tmp/ipykernel_13211/1200065306.py:27" *) $signed(x_in);
  (* src = "/tmp/ipykernel_13211/1200065306.py:8" *)
  always @(posedge clk)
    x_out <= \$5 ;
  (* src = "/tmp/ipykernel_13211/1200065306.py:12" *)
  always @(posedge clk)
    acc <= \$6 ;
  assign \$1  = w == (* src = "/tmp/ipykernel_13211/1200065306.py:24" *) 1'h1;
  assign \$2  = w == (* src = "/tmp/ipykernel_13211/1200065306.py:26" *) 2'h3;
  assign \$3  = $signed(acc) + (* src = "/tmp/ipykernel_13211/1200065306.py:25" *) $signed(x_in);
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$4 ) begin end
    \$5  = x_in;
    if (rst) begin
      \$5  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$4 ) begin end
    \$6  = acc;
    casez ({ en, 1'h0 })
      2'b1?:
          if (\$1 ) begin
            \$6  = \$3 [15:0];
          end else if (\$2 ) begin
            \$6  = \$4 [15:0];
          end
    endcase
    if (rst) begin
      \$6  = 16'h0000;
    end
  end
  assign clear = 1'h0;
endmodule

(* src = "/tmp/ipykernel_13211/1200065306.py:15" *)
(* generator = "Amaranth" *)
module \tt_um_lacesse_npu.npu.array.mac10 (rst, x_in, en, w, x_out, acc, clk);
  reg \$auto$verilog_backend.cc:2355:dump_module$5  = 0;
  wire \$1 ;
  wire \$2 ;
  wire [16:0] \$3 ;
  wire [16:0] \$4 ;
  reg [7:0] \$5 ;
  reg [15:0] \$6 ;
  (* src = "/tmp/ipykernel_13211/1200065306.py:12" *)
  output [15:0] acc;
  reg [15:0] acc = 16'h0000;
  (* src = "/tmp/ipykernel_13211/1200065306.py:10" *)
  wire clear;
  (* src = "/tmp/ipykernel_13211/2392253499.py:48" *)
  input clk;
  wire clk;
  (* src = "/tmp/ipykernel_13211/1200065306.py:11" *)
  input en;
  wire en;
  (* src = "/tmp/ipykernel_13211/2392253499.py:48" *)
  input rst;
  wire rst;
  (* src = "/tmp/ipykernel_13211/1200065306.py:9" *)
  input [1:0] w;
  wire [1:0] w;
  (* src = "/tmp/ipykernel_13211/1200065306.py:7" *)
  input [7:0] x_in;
  wire [7:0] x_in;
  (* src = "/tmp/ipykernel_13211/1200065306.py:8" *)
  output [7:0] x_out;
  reg [7:0] x_out = 8'h00;
  assign \$4  = $signed(acc) - (* src = "/tmp/ipykernel_13211/1200065306.py:27" *) $signed(x_in);
  (* src = "/tmp/ipykernel_13211/1200065306.py:8" *)
  always @(posedge clk)
    x_out <= \$5 ;
  (* src = "/tmp/ipykernel_13211/1200065306.py:12" *)
  always @(posedge clk)
    acc <= \$6 ;
  assign \$1  = w == (* src = "/tmp/ipykernel_13211/1200065306.py:24" *) 1'h1;
  assign \$2  = w == (* src = "/tmp/ipykernel_13211/1200065306.py:26" *) 2'h3;
  assign \$3  = $signed(acc) + (* src = "/tmp/ipykernel_13211/1200065306.py:25" *) $signed(x_in);
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$5 ) begin end
    \$5  = x_in;
    if (rst) begin
      \$5  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$5 ) begin end
    \$6  = acc;
    casez ({ en, 1'h0 })
      2'b1?:
          if (\$1 ) begin
            \$6  = \$3 [15:0];
          end else if (\$2 ) begin
            \$6  = \$4 [15:0];
          end
    endcase
    if (rst) begin
      \$6  = 16'h0000;
    end
  end
  assign clear = 1'h0;
endmodule

(* src = "/tmp/ipykernel_13211/1200065306.py:15" *)
(* generator = "Amaranth" *)
module \tt_um_lacesse_npu.npu.array.mac11 (rst, en, w, x_in, acc, clk);
  reg \$auto$verilog_backend.cc:2355:dump_module$6  = 0;
  wire \$1 ;
  wire \$2 ;
  wire [16:0] \$3 ;
  wire [16:0] \$4 ;
  reg [7:0] \$5 ;
  reg [15:0] \$6 ;
  (* src = "/tmp/ipykernel_13211/1200065306.py:12" *)
  output [15:0] acc;
  reg [15:0] acc = 16'h0000;
  (* src = "/tmp/ipykernel_13211/1200065306.py:10" *)
  wire clear;
  (* src = "/tmp/ipykernel_13211/2392253499.py:48" *)
  input clk;
  wire clk;
  (* src = "/tmp/ipykernel_13211/1200065306.py:11" *)
  input en;
  wire en;
  (* src = "/tmp/ipykernel_13211/2392253499.py:48" *)
  input rst;
  wire rst;
  (* src = "/tmp/ipykernel_13211/1200065306.py:9" *)
  input [1:0] w;
  wire [1:0] w;
  (* src = "/tmp/ipykernel_13211/1200065306.py:7" *)
  input [7:0] x_in;
  wire [7:0] x_in;
  (* src = "/tmp/ipykernel_13211/1200065306.py:8" *)
  reg [7:0] x_out = 8'h00;
  assign \$4  = $signed(acc) - (* src = "/tmp/ipykernel_13211/1200065306.py:27" *) $signed(x_in);
  (* src = "/tmp/ipykernel_13211/1200065306.py:8" *)
  always @(posedge clk)
    x_out <= \$5 ;
  (* src = "/tmp/ipykernel_13211/1200065306.py:12" *)
  always @(posedge clk)
    acc <= \$6 ;
  assign \$1  = w == (* src = "/tmp/ipykernel_13211/1200065306.py:24" *) 1'h1;
  assign \$2  = w == (* src = "/tmp/ipykernel_13211/1200065306.py:26" *) 2'h3;
  assign \$3  = $signed(acc) + (* src = "/tmp/ipykernel_13211/1200065306.py:25" *) $signed(x_in);
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$6 ) begin end
    \$5  = x_in;
    if (rst) begin
      \$5  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$6 ) begin end
    \$6  = acc;
    casez ({ en, 1'h0 })
      2'b1?:
          if (\$1 ) begin
            \$6  = \$3 [15:0];
          end else if (\$2 ) begin
            \$6  = \$4 [15:0];
          end
    endcase
    if (rst) begin
      \$6  = 16'h0000;
    end
  end
  assign clear = 1'h0;
endmodule
